import fs from 'node:fs';import path from 'node:path';import {domains,packages,featured,objects,sources,claims,exhibitions} from './data.mjs';
import {auditDate,rightsTaxonomy,sourceSurfaces,buildExcavation} from './excavation.mjs';
import {buildAssetKits,carouselCsv,motionMarkdown} from './asset-kits.mjs';
import {renderAssetExports} from './render-assets.mjs';
const root=path.resolve('.'), out=path.join(root,'dist');fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});
const site=(process.env.PUBLIC_SITE_URL||'https://institutions-of-one-fashion.vercel.app').replace(/\/$/,'');
const corrections='https://github.com/rn-collins/institutions-of-one-fashion/issues/new?template=correction-or-takedown.yml';
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const nav=`<a class="skip" href="#main">Skip to content</a><header><a class="wordmark" href="/">I/1 <i>×</i> FASHION</a><button class="nav-toggle" type="button" aria-expanded="false" aria-controls="primary-navigation">Menu</button><nav id="primary-navigation" aria-label="Primary"><a href="/build">Build</a><a href="/carry">Carry</a><a href="/control">Control</a><a href="/continue">Continue</a><a href="/evidence">Evidence</a><a href="/excavation">Excavation</a><a href="/tools">Tools</a></nav></header>`;
function shell(title,desc,body,slug=''){const canonical=site+(slug?`/${slug}`:'/'),schema=slug.startsWith('packages/')?'Article':slug==='tools'?'WebApplication':'CollectionPage';return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · Institutions of One × Fashion</title><meta name="description" content="${esc(desc)}"><link rel="canonical" href="${canonical}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:type" content="website"><meta property="og:url" content="${canonical}"><meta name="twitter:card" content="summary"><link rel="stylesheet" href="/assets/site.css"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':schema,name:title,headline:title,description:desc,url:canonical,author:{'@type':'Person',name:'RN Collins'},datePublished:'2026-09-07',dateModified:auditDate,publisher:{'@type':'Person',name:'RN Collins'}})}</script></head><body class="${slug.split('/')[0]||'home'}">${nav}<main id="main">${body}</main><footer><p>Institutions of One × Fashion · A field exhibition by RN Collins</p><p><a href="/rights">Rights desk</a> · <a href="/excavation">Excavation record</a> · <a href="/about">Method</a> · <a href="/evidence-assets.json">Evidence-assets manifest</a> · <a href="${corrections}">Request a correction or takedown ↗</a></p></footer><script src="/assets/tool-core.js"></script><script src="/assets/site.js"></script></body></html>`}
const card=p=>`<article class="card" data-domain="${p.domain}" data-text="${(p.id+' '+p.title+' '+p.summary).toLowerCase()}"><span>${p.id} · ${p.status}</span><h3>${esc(p.title)}</h3><p>${esc(p.summary)}</p>${featured.includes(p.id)?`<a href="/packages/${p.id.toLowerCase()}">Enter dossier <span aria-hidden="true">↗</span></a>`:'<em>Package mapped</em>'}</article>`;
const localImage=o=>`/media/${o.id}.jpg`;
const objectCard=o=>`<figure class="object"><div class="object-field"><img src="${localImage(o)}" alt="${esc(o.alt)}" loading="lazy"><span>RIGHTS-CLEARED PUBLIC COLLECTION</span></div><figcaption><h3>${esc(o.title)}</h3><p>${esc(o.maker)} · ${esc(o.date)} · ${esc(o.medium)}</p><p>${esc(o.caption)}</p><dl><dt>Identifier</dt><dd>${esc(o.accession)}</dd><dt>Credit</dt><dd>${esc(o.credit)}</dd><dt>Rights</dt><dd>${esc(o.license)}</dd><dt>Source</dt><dd><a href="${o.url}">Canonical object record ↗</a></dd></dl><p class="object-actions"><a href="${localImage(o)}" download="${o.id}.jpg">Download exhibition image ↓</a> · <a href="${o.image}">Institution-served file ↗</a></p></figcaption></figure>`;
const objectCards=objects.map(objectCard).join('');
const homeFeaturedIds=['B01','B06','CA01','CA07','CO01','CO10','CN01','CN12'];
const homeObjectIds=['81112','loc-gtfy-00717','loc-tofr-08422','80430'];
const homeObjectCards=objects.filter(o=>homeObjectIds.includes(o.id)).map(objectCard).join('');
const objectPackages={'83877':['CO08','CA04'],'157996':['CA02','CA10'],'106420':['CN04','CO06','CA03','B03'],'81112':['B01','B10','B05'],'loc-gtfy-00717':['CO02'],'loc-tofr-08422':['CO03','CA05'],'loc-ppmsca-44953':['CO07','CA01','CA06','B04'],'loc-pga-06009':['CO01'],'159187':['CO04','B02'],'155989':['CN02'],'80430':['CN04'],'84652':['CN01'],'loc-tofr-52127':['CA07'],'81630':['CA08'],'159303':['CA08'],'159172':['CA09'],'107061':['CO08','CO09','B09'],'159180':['B02','B03','CA03','CA08']};
const {candidates,reports}=buildExcavation({packages,exhibitions,claims,sources,objects,objectPackages});
const {kits:assetKits,corpusDisposition}=buildAssetKits({packages,exhibitions,candidates});
const home=`<section class="hero"><p class="eyebrow">A public research exhibition · 44 dossiers</p><h1>One hand.<br>Four rooms.<br>An institution.</h1><p class="dek">Fashion makes singular authority visible. This exhibition asks what allows that authority to become legible, transferable, owned, and alive beyond one body.</p><a class="enter" href="/build">Enter the first room</a></section><section class="rooms">${domains.map((d,i)=>`<a class="room" href="/${d.slug}"><small>0${i+1} · ${d.count} dossiers</small><h2>${d.name}</h2><p>${d.q}</p><span>${d.tone} →</span></a>`).join('')}</section><section class="thesis"><p>Not biography. Not brand worship.</p><h2>The subject is institutional engineering.</h2></section><section><div class="section-head"><p>Curated dossier path</p><h2>Eight points of entry</h2></div><div class="grid">${packages.filter(p=>homeFeaturedIds.includes(p.id)).map(card).join('')}</div></section><section><div class="section-head"><p>Material witnesses</p><h2>Four objects, four institutional problems</h2></div><div class="objects">${homeObjectCards}</div><p><a class="enter" href="/evidence">Enter the full 16-object evidence collection</a></p></section>`;
fs.writeFileSync(path.join(out,'index.html'),shell('One hand. Four rooms. An institution.','An evidence-led fashion exhibition about Build, Carry, Control, and Continue.',home.replace('full 16-object evidence collection','full 18-object evidence collection')));
for(const d of domains){const ps=packages.filter(p=>p.domain===d.slug);const body=`<section class="room-hero"><p>${d.tone} · ${d.count} dossiers</p><h1>${d.name}</h1><blockquote>${d.q}</blockquote></section><section class="catalog"><div class="filters"><label>Search this room <input type="search" data-search placeholder="Title, ID, question"></label><p aria-live="polite" data-count>${ps.length} dossiers</p></div><div class="grid" data-grid>${ps.map(card).join('')}</div></section>`;fs.writeFileSync(path.join(out,`${d.slug}.html`),shell(d.name,d.q,body,d.slug));}
for(const id of featured){
  const p=packages.find(x=>x.id===id),d=domains.find(x=>x.slug===p.domain),cs=claims[id]||[],x=exhibitions[id],o=objects.find(v=>v.id===x.objectId);
  const sourceIds=[...new Set([...cs.flatMap(([, ,ids])=>ids),...x.movements.flatMap(m=>m[4])])];
  const sourceRecords=sourceIds.map(sourceId=>sources.find(s=>s.id===sourceId)).filter(Boolean);
  const report=reports.find(r=>r.packageId===id),candidateRecords=candidates.filter(c=>c.relatedPackages.includes(id));
  const assetKit=assetKits.find(k=>k.packageId===id);
  const mediaRecords=candidateRecords.filter(c=>c.candidateType==='reusable-image');
  const resourceRecords=candidateRecords.filter(c=>c.candidateType!=='reusable-image');
  const body=`<article class="dossier exhibition">
    <header class="exhibition-cover"><p class="eyebrow">${p.id} · ${d.name} exhibition · Publication candidate · Version 1.0 · 7 September 2026</p><p class="folio">${esc(x.kicker)}</p><h1>${p.title}</h1><p class="lead">${esc(x.thesis)}</p><a class="enter" href="#argument">Read the exhibition</a></header>
    <section id="argument" class="opening"><p class="section-number">00</p><h2>The proposition</h2>${x.intro.map(v=>`<p>${esc(v)}</p>`).join('')}</section>
    <section class="sequence"><div class="section-title"><p class="section-number">01–04</p><h2>The institutional sequence</h2></div>${x.movements.map(([no,title,text,label,ids])=>`<article class="movement"><p class="movement-no">${esc(no)}</p><h3>${esc(title)}</h3><p>${esc(text)}</p><div class="source-strip"><span class="label ${label.toLowerCase()}">${label}</span>${ids.map(s=>`<a href="/rights#${s}">${s}</a>`).join('')}</div></article>`).join('')}</section>
    <section class="witness"><figure><img src="${localImage(o)}" alt="${esc(o.alt)}" loading="lazy"><figcaption><p class="eyebrow">Material witness · Rights-cleared public collection</p><h2>${esc(o.title)}</h2><p>${esc(o.maker)} · ${esc(o.date)} · ${esc(o.medium)}</p><p>${esc(x.objectUse)}</p><dl><dt>Identifier</dt><dd>${esc(o.accession)}</dd><dt>Credit</dt><dd>${esc(o.credit)}</dd><dt>Rights</dt><dd>${esc(o.license)}</dd></dl><p class="object-actions"><a href="${o.url}">Canonical object record ↗</a> · <a href="${localImage(o)}" download="${o.id}.jpg">Download exhibition image ↓</a> · <a href="${o.image}">Institution-served file ↗</a></p></figcaption></figure></section>
    <section class="tension"><p class="section-number">COUNTERPOINT</p><h2>What this framework could get wrong</h2><p>${esc(x.tension)}</p></section>
    <section class="fieldwork"><div><p class="section-number">FIELDWORK</p><h2>Do the work now</h2><p>Use this as a working session, not a score.</p></div><ol>${x.fieldwork.map(v=>`<li>${esc(v)}</li>`).join('')}</ol><p><a class="enter" href="/tools#${id.toLowerCase()}-tool">Open the ${id} instrument</a></p></section>
    <section><h2>Claim ledger</h2>${cs.map(([text,label,ids])=>`<article class="claim"><span class="label ${label.toLowerCase()}">${label}</span><p>${text}</p><p class="citations">${ids.map(s=>`<a href="/rights#${s}">${s}</a>`).join(' · ')}</p></article>`).join('')}</section>
    <section class="source-room"><div class="section-title"><p class="section-number">READ / WATCH / VERIFY</p><h2>The source room</h2></div><div class="source-shelf">${sourceRecords.map(s=>`<article><span>${s.id} · ${esc(s.disposition)}</span><h3>${esc(s.title)}</h3><p>${esc(s.institution)} · ${esc(s.date)}</p><p>${esc(s.rights)}</p>${s.url?`<a href="${s.url}">Open canonical source ↗</a>`:`<a href="/rights#${s.id}">Review unresolved record</a>`}</article>`).join('')}</div></section>
    <section class="package-media"><div class="section-title"><p class="section-number">MEDIA LIBRARY</p><h2>Reusable material, with its conditions attached</h2></div><p class="scope-note">The narrative keeps one deliberate material witness. This library preserves every nonduplicative reusable image mapped to this package without turning the exhibition into an undifferentiated image dump.</p><div class="objects">${mediaRecords.map(c=>{const o=objects.find(v=>`OBJ-${v.id}`===c.id);return o?objectCard(o):''}).join('')}</div>${mediaRecords.length?``:`<p>No additional image passed the item-level reuse gate. Relevant protected media remains in the Resources Room as a canonical link.</p>`}</section>
    <section class="source-room resources-room"><div class="section-title"><p class="section-number">RESOURCES ROOM</p><h2>Archives, records, tools and learning</h2></div><div class="source-shelf">${resourceRecords.map(c=>`<article><span>${esc(c.id)} · ${esc(c.disposition)}</span><h3>${esc(c.title)}</h3><p>${esc(c.institution)} · ${esc(c.date)}</p><p>${esc(c.rights)}</p>${c.canonicalUrl?`<a href="${c.canonicalUrl}">Open canonical resource ↗</a>`:'<b>Canonical item unresolved; discovery record retained.</b>'}</article>`).join('')}</div></section>
    <section class="asset-kit"><div class="section-title"><p class="section-number">PUBLICATION ASSET KIT · v2.0</p><h2>Every channel has a finished visual sequence</h2></div><p>Two distinct Instagram carousels, four Pinterest pins, a YouTube thumbnail, a vertical storyboard, a motion evidence plan, Beehiiv and LinkedIn media plans, and the package instrument are bound to exact asset IDs and rights treatments.</p><div class="export-preview">${['a/frame-01','a/frame-02','b/frame-01','b/frame-02'].map((v,i)=>`<figure><img src="/exports/${id.toLowerCase()}/instagram/${v}.png" alt="Preview of ${i<2?'carousel A':'carousel B'} frame ${(i%2)+1} for ${esc(p.title)}" loading="lazy"><figcaption>${i<2?'Carousel A':'Carousel B'} · frame ${(i%2)+1}</figcaption></figure>`).join('')}<figure><img src="/exports/${id.toLowerCase()}/youtube-thumbnail.png" alt="YouTube thumbnail for ${esc(p.title)}" loading="lazy"><figcaption>YouTube thumbnail</figcaption></figure><figure><img src="/exports/${id.toLowerCase()}/vertical-storyboard.png" alt="Vertical storyboard for ${esc(p.title)}" loading="lazy"><figcaption>Vertical storyboard</figcaption></figure></div><div class="asset-sequences">${[['Carousel A',assetKit.instagram.carouselA],['Carousel B',assetKit.instagram.carouselB]].map(([name,c])=>`<article><h3>${name} · ${esc(c.title)}</h3><ol>${c.frames.map(f=>`<li><b>${f.frame}. ${esc(f.role)}</b><span>${esc(f.assetId)} · ${esc(f.visualType)}</span><p>${esc(f.caption)}</p><small>${esc(f.credit)} · ${esc(f.disposition)}</small></li>`).join('')}</ol></article>`).join('')}</div><p><a href="/exports/${id.toLowerCase()}-publication-assets.zip" download>Download complete PNG set ↓</a> · <a href="/asset-kits/${id.toLowerCase()}.json" download>Complete asset kit JSON ↓</a> · <a href="/downloads/${id}-carousel-manifests.csv" download>Two carousel manifests ↓</a> · <a href="/downloads/${id}-motion-media-plan.md" download>Motion + media plan ↓</a></p></section>
    <section class="exhaustion-report"><div class="section-title"><p class="section-number">EXCAVATION REPORT · ${auditDate}</p><h2>What was searched—and where the claim stops</h2></div><p><b>${report.status.replaceAll('_',' ')}</b></p><p>${esc(report.scope)}</p><dl><dt>Registered surfaces</dt><dd>${report.surfaces.length}</dd><dt>Recorded candidates</dt><dd>${report.candidateIds.length}</dd><dt>Reusable media</dt><dd>${report.reusableIds.length}</dd><dt>Linked resources</dt><dd>${report.resourceIds.length}</dd></dl><p>${esc(report.stoppingRule)}</p><p><a href="/exhaustion/${id.toLowerCase()}.json" download>Download the package exhaustion report ↓</a> · <a href="/excavation">Read the collection method</a></p></section>
    <section class="deliverables"><p class="section-number">PACKAGE SYSTEM</p><h2>One inquiry, six publishing forms</h2><ul>${x.outputs.map(v=>`<li>${esc(v)}</li>`).join('')}</ul>${x.platform?`<div class="platform-copy"><h3>Finished platform treatments</h3>${x.platform.map((v,i)=>`<article><span>0${i+1}</span><p>${esc(v)}</p></article>`).join('')}</div>`:''}<p><b>By RN Collins · Publication candidate v1.0 · 7 September 2026.</b> Editorial, evidence, rights, accessibility, and production architecture are complete. Recording, bespoke photography, participant verification, counsel or specialist review where indicated, and RN owner-final approval remain human publication gates.</p><p><a href="/downloads/${id}-package-brief.md" download>Package brief ↓</a> · <a href="/downloads/${id}-evidence-register.csv" download>Evidence register ↓</a>${x.platform?` · <a href="/downloads/${id}-platform-kit.md" download>Platform kit ↓</a>`:''}</p></section>
    <aside class="claim-note"><b>Reading protocol</b><p>Every material statement carries an evidence label and point-of-claim source links. Interpretation is never presented as source fact. Legal sections identify their jurisdiction; state, foreign, contractual, beneficial-ownership, validity, priority, and disputed-fact questions remain counsel-review gates. This exhibition is educational and does not provide legal, conservation, or business advice.</p></aside>
  </article>`;
  fs.mkdirSync(path.join(out,'packages'),{recursive:true});fs.writeFileSync(path.join(out,'packages',`${id.toLowerCase()}.html`),shell(p.title,x.thesis,body,`packages/${id.toLowerCase()}`));
}
const rights=`<section class="room-hero"><p>${sources.length}-source rights desk</p><h1>Evidence has conditions.</h1><blockquote>Publicly visible is not the same as reusable.</blockquote></section><section class="ledger"><div class="filters"><label>Search sources <input type="search" data-search placeholder="Institution, title, rights"></label><label>Disposition <select data-rights><option value="all">All dispositions</option>${[...new Set(sources.map(s=>s.disposition))].map(x=>`<option>${x}</option>`).join('')}</select></label><button type="button" data-reset>Reset</button><p data-count aria-live="polite">${sources.length} records</p></div><div data-grid>${sources.map(s=>`<article class="source" id="${s.id}" data-right="${s.disposition}" data-text="${(s.id+' '+s.title+' '+s.institution+' '+s.rights+' '+s.disposition).toLowerCase()}"><span>${s.id} · ${s.disposition}</span><h2>${esc(s.title)}</h2><p>${esc(s.institution)} · ${esc(s.date)}</p><p>${esc(s.rights)}</p><p>Retrieved ${s.retrieved}</p>${s.url?`<a href="${s.url}">Canonical source ↗</a>`:`<p><b>Exact canonical record unresolved.</b> ${s.discoveryUrl?`<a href="${s.discoveryUrl}">Shared discovery portal ↗</a>`:''}</p>`}</article>`).join('')}</div></section>`;fs.writeFileSync(path.join(out,'rights.html'),shell('Rights desk',`A ${sources.length}-source point-of-claim rights ledger.`,rights,'rights'));
const evidence=`<section class="room-hero"><p>Object-level source protocol</p><h1>Evidence, not atmosphere.</h1><blockquote>Every object keeps its identifier, caption, rights, alt text, and canonical source.</blockquote></section><section class="objects">${objectCards}</section><section><h2>Machine-readable manifest</h2><p><a class="enter" href="/evidence-assets.json" download>Download evidence-assets.json</a></p></section>`;fs.writeFileSync(path.join(out,'evidence.html'),shell('Evidence',`${objects.length} rights-cleared public-collection objects with complete source and rights metadata.`,evidence,'evidence'));
const excavation=`<section class="room-hero"><p>44 package reports · ${candidates.length} recorded candidates · ${sourceSurfaces.length} source surfaces</p><h1>The search has a boundary.</h1><blockquote>Exhaustive means every registered surface and query is accounted for—not every item on the internet.</blockquote></section><section class="prose"><h2>The rights taxonomy</h2><dl>${rightsTaxonomy.map(r=>`<dt>${r.code.replaceAll('_',' ')}</dt><dd>${esc(r.treatment)}</dd>`).join('')}</dl></section><section class="surface-register"><div class="section-head"><p>Dated ${auditDate}</p><h2>Source-surface registry</h2></div><div class="source-shelf">${sourceSurfaces.map(s=>`<article><span>${s.id} · ${esc(s.kind)}</span><h3>${esc(s.name)}</h3><p><b>Query frame:</b> ${esc(s.query)}</p><p><b>Rights gate:</b> ${esc(s.rightsGate)}</p>${s.url?`<a href="${s.url}">Open registry surface ↗</a>`:'<p>Exact official entity URL is recorded per candidate.</p>'}</article>`).join('')}</div></section><section class="surface-register"><div class="section-head"><p>Package-level proof</p><h2>44 dated exhaustion reports</h2></div><div class="grid">${reports.map(r=>`<article class="card"><span>${r.packageId} · ${r.status.replaceAll('_',' ')}</span><h3>${esc(r.title)}</h3><p>${r.candidateIds.length} candidates · ${r.reusableIds.length} reusable · ${r.resourceIds.length} linked resources</p><a href="/exhaustion/${r.packageId.toLowerCase()}.json">Open report ↗</a></article>`).join('')}</div></section><section class="prose"><h2>Download the audit corpus</h2><p><a class="enter" href="/excavation/source-surfaces.json" download>Source surfaces ↓</a> <a class="enter" href="/excavation/candidate-ledger.json" download>Candidate ledger ↓</a> <a class="enter" href="/excavation/exhaustion-index.json" download>Exhaustion index ↓</a></p></section>`;
fs.writeFileSync(path.join(out,'excavation.html'),shell('Excavation record','The dated source-surface registry, candidate ledger, rights taxonomy and 44 package-level exhaustion reports.',excavation,'excavation'));
fs.mkdirSync(path.join(out,'excavation'),{recursive:true});
fs.writeFileSync(path.join(out,'excavation','source-surfaces.json'),JSON.stringify({version:'1.0.0',auditDate,scope:'Finite documented search registry; not the entire internet.',rightsTaxonomy,sourceSurfaces},null,2));
fs.writeFileSync(path.join(out,'excavation','candidate-ledger.json'),JSON.stringify({version:'1.0.0',auditDate,count:candidates.length,candidates},null,2));
fs.writeFileSync(path.join(out,'excavation','exhaustion-index.json'),JSON.stringify({version:'1.0.0',auditDate,count:reports.length,reports:reports.map(r=>({packageId:r.packageId,title:r.title,status:r.status,report:`/exhaustion/${r.packageId.toLowerCase()}.json`}))},null,2));
fs.writeFileSync(path.join(out,'excavation','candidate-destinations.json'),JSON.stringify({version:'2.0',auditDate,count:corpusDisposition.length,candidates:corpusDisposition},null,2));
fs.mkdirSync(path.join(out,'asset-kits'),{recursive:true});for(const kit of assetKits)fs.writeFileSync(path.join(out,'asset-kits',`${kit.packageId.toLowerCase()}.json`),JSON.stringify(kit,null,2));
fs.mkdirSync(path.join(out,'exhaustion'),{recursive:true});for(const report of reports)fs.writeFileSync(path.join(out,'exhaustion',`${report.packageId.toLowerCase()}.json`),JSON.stringify(report,null,2));
const tools=[
{slug:'house-threshold',name:'House Threshold Diagnostic',id:'B01',checks:['Aesthetic rules have examples and exceptions','Atelier roles and handoffs are named','Records persist beyond one collection','Core assets have accountable owners'],note:'Which decision still depends only on the founder’s memory?'},
{slug:'archive-activation',name:'Archive Activation Simulator',id:'CA02',checks:['Origin record is retrievable','Rights permit the intended treatment','Interpretation is separated from source fact','Transformation keeps a citation trail'],note:'What will this record teach the next collection?'},
{slug:'name-control',name:'Name Control Inventory',id:'CO01',checks:['Personal and company names are distinguished','Marks, domains, and handles have named owners','Territory and use classes are recorded','Counsel questions are separated from conclusions'],note:'Which identity asset has unclear control or continuity?'},
{slug:'living-archive',name:'Living Archive Sprint',id:'CN04',checks:['Physical and digital objects share identifiers','Decision context is captured in the founder’s voice','File formats and backups are documented','Rights, privacy, and successor access are recorded'],note:'What must be narrated now because the file cannot explain it?'}];
tools.push(
{slug:'brand-institution-gap',name:'Brand / Institution Gap Audit',id:'B10',checks:['Public promise is stated plainly','Fulfillment system is documented','Core assets have accountable owners','Seventy-two-hour absence test passes'],note:'Where does recognition still depend on constant founder performance?'},
{slug:'constellation-mapper',name:'Creative Constellation Mapper',id:'CA10',checks:['Every material decision has a role','Credits travel with the work','Missing labor is marked unresolved','Consent and correction routes are recorded'],note:'Whose knowledge disappears if the public record keeps only one name?'},
{slug:'audience-portability',name:'Audience Portability Map',id:'CO06',checks:['Account ownership and administrators are verified','Recovery works without one device','Original content is archived','Alternate consent-based route exists'],note:'Which audience relationship exists only inside one platform?'},
{slug:'taste-trace',name:'Taste Trace Ledger',id:'CO08',checks:['Claimed element is defined precisely','Inputs and permissions are recorded','Human selection and edits are described','Counsel-review questions are separated'],note:'What can the evidence show—and what remains a legal or ethical question?'}
);
tools.push(
{slug:'creative-economic-control',name:'Creative / Economic Control Matrix',id:'CO02',checks:['Creative powers are written as verb plus object','Board and delegated authority records are attached','Voting and economic rights are mapped separately','Departure and override scenarios have counsel gates'],note:'Which claimed power disappears when the title, contract, vote, or equity changes?'},
{slug:'runway-image-envelope',name:'Runway Image Rights Envelope',id:'CO03',checks:['Exact file, author, source and metadata are preserved','Work-made-for-hire and transfer evidence are attached','Credential, model, venue and embargo terms are checked','Crop, platform, credit, alt and archive use are approved'],note:'Which permission layer is unknown, expired, territory-limited, or still with counsel?'},
{slug:'clause-institution',name:'Clause-to-Institution Simulator',id:'CO07',checks:['Inputs, deliverables and named approvers are defined','Payment, ownership, license and credit are separated','Source files, records, access and archive copies are allocated','Termination, transition and dispute scenarios are tested'],note:'Which human action changes when this clause changes?'}
);
tools.push(
{slug:'archive-rights-constellation',name:'Archive Rights Constellation',id:'CO04',checks:['Each object and file has a stable identifier','Custody and physical title are separately recorded','Copyright, contract, privacy and access evidence are attached','Use verbs point to records and unresolved matters point to counsel'],note:'Which claimed power is supported only by possession rather than a governing record?'},
{slug:'succession-archive-readiness',name:'Succession Archive Readiness',id:'CN04',checks:['Decision context is captured in the founder’s voice','Physical and digital relatives share identifiers','Two verified copies and format risks are documented','Stewards, alternates, privacy and review authority are named'],note:'What knowledge or access would disappear after seventy-two hours of founder absence?'},
{slug:'legacy-authority-matrix',name:'Legacy Authority Matrix',id:'CN02',checks:['The proposed interpretive act is named precisely','Every authority claim has a source record','Legal, corporate, curatorial, craft and cultural scopes stay distinct','Dissent, correction and periodic review are defined'],note:'Who may do what—and which authority would be wrongly implied by that choice?'},
{slug:'house-continuity-stress-test',name:'House Continuity Stress Test',id:'CN01',checks:['People, obligations, money, facilities and accounts have backups','Corporate, IP, estate and archive authority are mapped','Values, methods, motifs and habits are distinguished','Continue, pause, license, sell, donate and close are compared'],note:'Which decision becomes unauthorized, impossible, or invisible when the founder is absent?'}
);
tools.push(
{slug:'collection-constellation',name:'Collection Constellation Mapper',id:'CA01',checks:['Every verified contributor and entity is named','Each consequential handoff has a source record','Credit, pay, authorship, ownership and approval are separate','Contributors have privacy and correction routes'],note:'Whose labor, knowledge, or power disappears when the public record keeps only the headline name?'},
{slug:'pattern-decision-ledger',name:'Pattern Decision Ledger',id:'CA03',checks:['Brief and non-negotiable design intent are attached','Every pattern change has a reason and decision-maker','Fit and size assumptions are explicit','Pattern files, narration, credit and access survive'],note:'Which skilled decision is visible in the garment but absent from its record?'},
{slug:'vision-production-handoff',name:'Vision-to-Production Handoff Map',id:'CA04',checks:['Every entity, jurisdiction and worker relationship is verified','Specifications preserve both requirement and reason','Approval, change, payment and remedy thresholds are explicit','Production feedback changes the next version and archive'],note:'Where did information, money, authority, or risk move without an accountable record?'},
{slug:'narrative-infrastructure',name:'Narrative Infrastructure Ledger',id:'CA05',checks:['Every public claim has evidence and an approver','Relationships, access, conflicts and disclosures are mapped','Names, images, quotes and persona uses have permission status','Errors, corrections, refusals and learning enter the archive'],note:'What became publicly legible—and who gained or lost power through that frame?'}
);
tools.push(
{slug:'debut-readiness',name:'Debut Readiness Ledger',id:'B06',checks:['The collection question and revision condition are explicit','Prototype failures and decisions are preserved','Participant role, pay, credit and permission are verified','Rights, fulfillment, accessibility and archive gates pass'],note:'Which invisible prerequisite could still break the public promise?'},
{slug:'independent-research',name:'Independent Research Desk',id:'B07',checks:['Every question can change a design decision','Canonical records and rights statements are retained','Observation, inference and transformation stay separate','Counterevidence and cultural review are recorded'],note:'Which reference is visually persuasive but evidentially weak or unavailable for reuse?'},
{slug:'counterpart-capacity',name:'Counterpart Capacity Matrix',id:'B08',checks:['Operational work is named rather than called support','Creative, executive, board and voting powers are separate','Economics and information access have evidence','Deadlock, departure and incapacity have counsel gates'],note:'Which responsibility or authority exists only as an unwritten expectation?'},
{slug:'season-signal',name:'Season Signal Comparator',id:'B09',checks:['The comparison set and missing records are disclosed','Observable codes are separated from interpretation','Counterexamples and collaborators are included','Cultural recognition and legal protection stay distinct'],note:'Which claimed code disappears when the least recognizable season is included?'}
);
tools.push(
{slug:'styling-meaning-ledger',name:'Styling Meaning Ledger',id:'CA06',checks:['Selections, refusals, references and reasons are recorded','Every contributor has a verified role and correction route','Credit, fee, approval, ownership and license remain separate','Community references have cultural-authority review'],note:'Which styling decision changed the meaning—and whose authority or labor is missing from the record?'},
{slug:'house-image-grammar',name:'House Image Grammar Atlas',id:'CA07',checks:['Creator and full production credits are preserved','Visual patterns are separated from legal conclusions','Work-made-for-hire, transfer and license evidence are attached','Files, selects, releases, expiry and archive custody are mapped'],note:'Which image-layer is culturally powerful but legally or archivally unresolved?'},
{slug:'craft-obligation',name:'Craft Obligation Ledger',id:'CA08',checks:['Roles are named only with evidence and safe consent','Price, lead time, revision, overtime and payment are traced','Safety, worker voice, grievance and remedy routes are verified','Knowledge capture includes permission, benefit and cultural review'],note:'Where does admiration for craft conceal a missing labor obligation?'},
{slug:'tacit-transfer',name:'Tacit Knowledge Transfer Protocol',id:'CA09',checks:['Demonstration, attempt, correction and variation are paired','Participation, labor, safety and compensation are documented','Confidentiality, cultural authority and non-recording choices are honored','Access, archive custody, teaching rights and revocation are governed'],note:'What can responsibly travel—and what must remain with its practitioner or community?'}
);
tools.push(
{slug:'code-counterexample-atlas',name:'House Code Counterexample Atlas',id:'B02',checks:['Twenty-work sample spans multiple moments','Every proposed code has counterexamples','Collaborator and influence records are attached','Cultural recognition is separated from legal rights'],note:'Which exception proves the code is alive—and which claim is broader than its evidence?'},
{slug:'taste-transmission',name:'Taste Transmission Protocol',id:'B03',checks:['Judgment context and rejected options are recorded','Demonstration, attempt and correction are paired','Dissent and override authority survive','Consent, benefit, access and withdrawal are governed'],note:'Whose knowledge is being carried, and who may refuse its capture or reuse?'},
{slug:'aesthetic-operating-loop',name:'Aesthetic Operating Loop',id:'B04',checks:['Inputs retain origin and permission','Rules name roles, tests and exceptions','Feedback and rejected signals are recorded','Exact protected assets are separated from broad style'],note:'Where does the aesthetic learn—and where does process quietly reproduce bias?'},
{slug:'pre-entity-institution',name:'Pre-Entity Institution Map',id:'B05',checks:['Recurring promises, people and payment paths are mapped','Parties on accounts and agreements are verified','Liability, tax, labor and jurisdiction triggers are flagged','Transition inventory is ready for professional review'],note:'Which institutional capacity exists now—and which protection is still only assumed?'}
);
for(const [id,x] of Object.entries(exhibitions))if(!tools.some(t=>t.id===id))tools.push({slug:`${id.toLowerCase()}-field-instrument`,name:x.outputs[4],id,checks:x.movements.map(m=>`${m[1]} — ${m[2].split('.')[0]}`),note:x.tension.split('.')[0]+'?'});
const baseDownloads=['series-editorial-standard.md','series-editorial-standard.csv','asset-rights-intake.md','asset-rights-intake.csv'];
const productionPackageIds=Object.keys(exhibitions);
const packageDownloads=productionPackageIds.flatMap(id=>[`${id}-package-brief.md`,`${id}-evidence-register.csv`,`${id}-platform-kit.md`,`${id}-carousel-manifests.csv`,`${id}-motion-media-plan.md`]);
// The four launch dossiers also preserve alternate Markdown/CSV working
// formats. Keep them visible instead of leaving valid production files hidden
// in the deployment.
const alternateLaunchDownloads=['B01','CA02','CO01','CN04'].flatMap(id=>[`${id}-package-brief.csv`,`${id}-evidence-register.md`]);
const visibleDownloads=[...baseDownloads,...packageDownloads,...alternateLaunchDownloads];
const toolsBody=`<section class="room-hero"><p>${tools.length} local-first instruments</p><h1>Tools that leave with you.</h1><blockquote>Selections remain in your browser. Downloads preserve checked and unchecked state, version, timestamp, and disclosure.</blockquote></section><section class="tool-grid">${tools.map(t=>`<form id="${t.id.toLowerCase()}-tool" class="tool" data-tool="${t.slug}" data-version="1.2"><p>${t.id}</p><h2>${t.name}</h2>${t.checks.map((x,i)=>`<label><input type="checkbox" name="check_${i+1}"> ${x}</label>`).join('')}<label>${t.note}<textarea name="working_note" rows="3"></textarea></label><div><button type="button" data-download="md">Download MD</button><button type="button" data-download="csv">Download CSV</button></div><small data-storage>Educational planning instrument; not legal advice. No data is transmitted.</small></form>`).join('')}</section><section id="production-files"><div class="section-head"><p>${visibleDownloads.length} finished editable files</p><h2>The publishing floor, downloadable</h2></div><div class="downloads">${visibleDownloads.map(n=>`<p><b>${n.replaceAll('-',' ').replace(/\.(md|csv)$/,'')}</b><a href="/downloads/${n}" download>${n.endsWith('.md')?'MD':'CSV'}</a></p>`).join('')}</div></section>`;fs.writeFileSync(path.join(out,'tools.html'),shell('Tools',`${tools.length} downloadable evidence tools and ${visibleDownloads.length} finished editable production files.`,toolsBody,'tools'));
const about=`<section class="room-hero"><p>Curatorial method</p><h1>Singular does not mean unsupported.</h1><blockquote>Build the method. Carry the intelligence. Control the leverage. Continue the work.</blockquote></section><section class="prose"><h2>Evidence labels</h2><dl><dt>VERIFIED</dt><dd>Supported directly by the linked source.</dd><dt>INFERENCE</dt><dd>A reasoned interpretation of verified evidence.</dd><dt>PROPOSAL</dt><dd>An original editorial or design recommendation.</dd><dt>UNRESOLVED</dt><dd>Requires reporting, permission, legal review, or confirmation.</dd></dl><h2>Asset rule</h2><p>No AI-generated imagery. A visual enters the exhibition only with an object-level title, creator or institution, canonical URL, date, identifier, evidentiary use, rights statement, credit, retrieval date, alt text, and local implementation decision.</p></section>`;fs.writeFileSync(path.join(out,'about.html'),shell('Method','The evidence and curatorial method for Institutions of One × Fashion.',about,'about'));
fs.writeFileSync(path.join(out,'404.html'),shell('Not found','This room does not exist.',`<section class="hero"><p class="eyebrow">404 · Uncatalogued</p><h1>This room<br>is not in<br>the archive.</h1><a class="enter" href="/">Return to the exhibition</a></section>`,'404'));
fs.mkdirSync(path.join(out,'assets'),{recursive:true});for(const f of ['site.css','site.js','tool-core.js'])fs.copyFileSync(path.join(root,'src',f),path.join(out,'assets',f));
fs.cpSync(path.join(root,'src','media'),path.join(out,'media'),{recursive:true});
fs.writeFileSync(path.join(out,'evidence-assets.json'),JSON.stringify({manifestVersion:'1.3.0',published:'2026-09-07',policy:'No AI-generated imagery. Object-level rights and the named institution\'s record govern.',policyUrls:['https://www.metmuseum.org/about-the-met/policies-and-documents/open-access','https://www.loc.gov/free-to-use/fashion/'],objects:objects.map(o=>({...o,sourceImage:o.image,image:localImage(o),download:localImage(o),retrieved:'2026-09-07',isRightsClearedForThisUse:true,implementationDecision:'LOCAL_ARCHIVAL_COPY_FOR_PUBLICATION',transformations:['responsive display sizing only'],relatedPackages:objectPackages[o.id]||[]}))},null,2));
fs.writeFileSync(path.join(out,'package-inventory.json'),JSON.stringify({version:'1.1.0',packages},null,2));
fs.writeFileSync(path.join(out,'source-manifest.json'),JSON.stringify({version:'1.1.0',sources},null,2));
fs.mkdirSync(path.join(out,'downloads'),{recursive:true});
const artifacts=[
{name:'B01-package-brief',purpose:'Turn the house threshold into a flagship essay, diagnostic, film and social sequence.',question:'What changes when “I make clothes” becomes an institution?',sources:'S11; S16; S21',claims:'House as operating condition; Cashin company formation',outputs:'3000-word essay; 8-minute film; 6-slide document; 9-frame carousel; 60-second diagnostic; worksheet',gate:'Verify every historical threshold and define house without implying legal status.'},
{name:'B01-evidence-register',purpose:'Track practice, method, roles, records and assets for the house-threshold argument.',question:'Which evidence demonstrates each threshold?',sources:'S11; S16; S21; MET-83877',claims:'Founder narration; institutional records; mature archive; object metadata',outputs:'Claim rows; object record; counterevidence memo',gate:'Link-only oral history; permission-sensitive archive media; Met object reusable.'},
{name:'CA02-package-brief',purpose:'Produce the archive-as-employee dossier and activation simulator.',question:'When does an archive become an active creative resource?',sources:'S21; S22; S35',claims:'Tapestry archive disclosure; Ferré research and digitization',outputs:'Dossier; scroll narrative; audio plan; case card; simulator; metadata linter',gate:'Separate Tapestry fact from editorial inference; do not reuse archive media.'},
{name:'CA02-evidence-register',purpose:'Map archive functions to exact records, rights and transformation limits.',question:'What proves archive use rather than archive possession?',sources:'S21; S22; S35; MET-157996',claims:'Retrieve; interpret; transform; cite',outputs:'Source matrix; rights decisions; metadata field map',gate:'SEC facts may be diagrammed; Google Arts & Culture remains link-only.'},
{name:'CO01-package-brief',purpose:'Build an educational name-control inventory without giving legal advice.',question:'Who owns the label name, marks, domains, handles, likeness and archive authority?',sources:'S28; S29; S30; S32',claims:'Distinct IP tools have distinct scope; identity assets require verified ownership',outputs:'Flagship article; name-system diagram; five shorts; database walkthrough; counsel-prep inventory',gate:'No legal conclusion, jurisdictional promise or copied WIPO assessment.'},
{name:'CO01-evidence-register',purpose:'Separate each identity asset, record source and unresolved ownership question.',question:'Which public record or agreement would establish control?',sources:'S28; S29; S30; S32',claims:'Trademark; design; copyright; patent; domain; likeness',outputs:'Asset-by-asset evidence rows; counsel handoff',gate:'Database results require saved query, retrieval time and disclaimer.'},
{name:'CN04-package-brief',purpose:'Produce a seven-day living-archive sprint while the founder can narrate decisions.',question:'Why begin preservation before estate administration?',sources:'S08; S39; S40; S41',claims:'Files need context; preservation requires inventory, description and planned storage',outputs:'3000-word guide; seven emails; audio prompts; pairing tool; before/after map',gate:'Not estate, conservation or legal advice; private user data stays local.'},
{name:'CN04-evidence-register',purpose:'Pair physical objects, digital files, rights and oral-history prompts.',question:'Which knowledge is absent from the file itself?',sources:'S08; S39; S40; S41; S42; S43',claims:'Identifier pairing; formats; storage; narration; access authority',outputs:'Seven-day action ledger; file/object pair register; referral triggers',gate:'Refer valuable or fragile textiles to a qualified conservator.'},
{name:'series-editorial-standard',purpose:'Apply the Build–Carry–Control–Continue and evidence-label method to every package.',question:'Does the package expose institutional engineering rather than profile a celebrity?',sources:'VERIFIED; INFERENCE; PROPOSAL; UNRESOLVED',claims:'Question gate; evidence gate; rights gate; counterevidence; four-domain audit',outputs:'Long; short; audio; video; interactive; education; source objects; corrections',gate:'No package publishes without rights, accessibility, expert and version gates.'},
{name:'asset-rights-intake',purpose:'Record one implementation decision for every visual, recording, document or quotation.',question:'Can this exact asset be reused, embedded, quoted, linked, or not used?',sources:'Canonical URL; persistent ID; displayed rights; creator; institution',claims:'Evidence use and reuse permission are separate determinations',outputs:'Caption; alt text; credit; transformation log; permission record; takedown contact',gate:'Unknown provenance or synthetic material is DO NOT USE.'}];
const q=v=>`"${String(v).replaceAll('"','""')}"`;
for(const a of artifacts){const title=a.name.replaceAll('-',' ');fs.writeFileSync(path.join(out,'downloads',a.name+'.md'),`# ${title}\n\nVersion: 1.1\nStatus: evidence-mapped production artifact\n\n## Purpose\n${a.purpose}\n\n## Governing question\n${a.question}\n\n## Evidence spine\n${a.sources}\n\n## Claim or field architecture\n${a.claims}\n\n## Production outputs\n${a.outputs}\n\n## Release gate\n${a.gate}\n\n## Accessibility and rights\nCaptions, transcripts, keyboard behavior, visible labels, exact canonical records, and object-level implementation decisions are mandatory.\n`);fs.writeFileSync(path.join(out,'downloads',a.name+'.csv'),`field,value,status\nartifact,${q(a.name)},complete\nversion,1.1,complete\npurpose,${q(a.purpose)},mapped\ngoverning_question,${q(a.question)},mapped\nsource_ids_or_fields,${q(a.sources)},mapped\nclaims_or_schema,${q(a.claims)},mapped\nproduction_outputs,${q(a.outputs)},mapped\nrelease_gate,${q(a.gate)},required\naccessibility,"captions; transcripts; keyboard; visible labels",required\nrights,"exact canonical record; item-level decision; transformation log",required\n`)}
for(const id of productionPackageIds){const x=exhibitions[id];const claimRows=claims[id].map(([t,l,s])=>`- **${l}:** ${t} (${s.join(', ')})`).join('\n');fs.writeFileSync(path.join(out,'downloads',`${id}-package-brief.md`),`# ${packages.find(p=>p.id===id).title}\n\n## Canonical thesis\n${x.thesis}\n\n## Complete editorial sequence\n${x.intro.join('\n\n')}\n\n${x.movements.map(m=>`### ${m[0]} — ${m[1]}\n${m[2]}\n\nEvidence: ${m[3]} · ${m[4].join(', ')}`).join('\n\n')}\n\n## Counterargument\n${x.tension}\n\n## Fieldwork\n${x.fieldwork.map((v,i)=>`${i+1}. ${v}`).join('\n')}\n\n## Release gates\nRecording/performance, any bespoke photography, participant verification, labor and contract review where flagged, and RN owner-final approval.\n`);fs.writeFileSync(path.join(out,'downloads',`${id}-evidence-register.csv`),`claim,label,source_ids,review\n${claims[id].map(([t,l,s])=>`${q(t)},${l},${q(s.join('; '))},point-of-claim`).join('\n')}\n`);fs.writeFileSync(path.join(out,'downloads',`${id}-platform-kit.md`),`# ${packages.find(p=>p.id===id).title} — finished platform kit\n\n${x.platform.map((v,i)=>`## ${i+1}. ${v.split(' — ')[0]}\n${v.split(' — ').slice(1).join(' — ')}`).join('\n\n')}\n\n## Claim ledger\n${claimRows}\n\n## Publication discipline\nDo not invent production arrangements or add unlicensed imagery. Preserve captions, alt text, creator and institution credits, canonical URLs, evidence labels, labor and jurisdiction limits, participant correction, and counsel or specialist gates.\n`)}
for(const kit of assetKits){fs.writeFileSync(path.join(out,'downloads',`${kit.packageId}-carousel-manifests.csv`),carouselCsv(kit));fs.writeFileSync(path.join(out,'downloads',`${kit.packageId}-motion-media-plan.md`),motionMarkdown(kit));}
const routes=['','build','carry','control','continue',...featured.map(id=>`packages/${id.toLowerCase()}`),'evidence','excavation','rights','tools','about'];fs.writeFileSync(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.map(r=>`<url><loc>${site}/${r}</loc></url>`).join('')}</urlset>`);fs.writeFileSync(path.join(out,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${site}/sitemap.xml\n`);
await renderAssetExports({root,out,kits:assetKits});
