import {sources} from './sources.mjs';
export {sources};
export const domains=[{slug:'build',name:'Build',count:10,q:'What makes the work recognizably yours—and what system produces it?',tone:'The atelier room'},{slug:'carry',name:'Carry',count:10,q:'How does the institution travel beyond your body without losing meaning?',tone:'The transmission room'},{slug:'control',name:'Control',count:12,q:'Who owns the name, work, evidence, access, and leverage?',tone:'The rights room'},{slug:'continue',name:'Continue',count:12,q:'What survives absence, sale, succession, or death?',tone:'The living archive'}];
const titles={build:['When Does a Designer Become a House?','The Founder’s Hand, Decoded','Atelier as Operating System','The Sample Is a Constitution','A Vocabulary You Can Hire Into','Collection One Is Not the Beginning','The Independent Designer’s Research Department','The Business Partner Beside the Name','Seven Seasons of Signal','From Client Work to Canon'],carry:['How the House Speaks When You Are Not in the Room','Archive as Design Employee','The Translation Layer','Carrying Craft Without Owning Every Hand','License Without Disappearance','The Lookbook as Institutional Memory','Wholesale Is a Governance Event','A House Across Platforms','Teaching the Eye','Metadata Is Merchandising for Memory'],control:['Your Name Is Not Necessarily Yours','The Control Garment','Four Rights in One Dress','The Archive Has an Owner','Controlled Company, Controlled Story','The Account Is an Asset','Collaboration Is an IP Event','The Copy, the Reference, the Archive','Proof of Making','The Product Passport Becomes the House Record','Sell the Company, Keep the Archive?','The Cost of Link-Only Culture'],continue:['The Founder Is a Single Point of Failure','Successor, Interpreter, or Impersonator?','The Last Collection Is an Operational Event','Archive Before Estate','Foundation, Museum, Company, or School?','Continue the Method, Not the Motif','The Oral History Is a Succession Document','A Garment Can Outlive Its File','Philanthropy as Continuation','The House After the House','Provenance Is Future Memory','The Institutional Will']};
const questions={build:['What changes when “I make clothes” becomes an institution?','Can tacit aesthetic judgment be documented without flattening it?','Which roles carry the designer’s intelligence?','What does a prototype decide about the future institution?','How do silhouette, color, material, finish, and refusal become teachable?','What invisible infrastructure precedes a debut?','How can one person build research rigor without pretending to be a conglomerate?','What institutional capacity is carried by the person not on the label?','How many repetitions create a recognizable code?','How do commissions become knowledge rather than one-offs?'],carry:['Which documents and rituals transmit judgment?','When does an archive become an active creative resource?','What must survive between runway idea and saleable product?','How can outside makers preserve house standards?','Which elements can travel into fragrance, accessories, home, or collaboration?','Is a lookbook marketing, record, specification, or all three?','What control leaves the house when distribution leaves the house?','Can the same codes survive runway, site, social, retail, and press?','What can successors learn from critique rather than imitation?','If a work cannot be found, can it influence the future?'],control:['Who owns the label name, marks, domains, and likeness?','How do equity and voting rights change creative power?','What can trademark, copyright, design rights, and patent each protect?','Who owns garments, sketches, photographs, recordings, metadata, and access rights?','What does founder voting control preserve—and prevent?','Who controls domains, handles, mailing lists, storefronts, and authentication?','What is created, borrowed, approved, and retained by each collaborator?','Where do influence, infringement, and archival reuse diverge?','What records establish authorship, date, development, and chain of custody?','Can compliance infrastructure also preserve provenance and care?','Which assets can and should be separated in a transaction?','What happens when a brand’s memory depends on platforms it does not own?'],continue:['Which decisions, relationships, and keys disappear with one person?','What gives a successor legitimacy?','What should happen to orders, staff, IP, files, samples, and promises after incapacity or death?','Why begin preservation while the founder can still describe decisions?','Which steward can preserve, interpret, teach, and fund a legacy?','How does a house evolve without copying visual signatures?','Which knowledge can only be captured in voice?','What must be preserved physically and digitally together?','Can resources reproduce conditions for future creators rather than reproduce a founder’s style?','What survives when the operating company closes?','What chain of evidence lets later audiences trust an object and its story?','What should a founder decide now about name, archive, creative authority, and public interpretation?']};
const prefixes={build:'B',carry:'CA',control:'CO',continue:'CN'};
export const packages=domains.flatMap(d=>titles[d.slug].map((title,i)=>({id:`${prefixes[d.slug]}${String(i+1).padStart(2,'0')}`,title,domain:d.slug,status:[0,1,2,9].includes(i)?'Evidence mapped':'Reporting queue',summary:questions[d.slug][i]})));
const nextTitles={B10:'A Personal Brand Is Not an Institution',CA10:'The Myth of the Lone Fashion Genius',CO06:'A Million Followers Is a Rented Institution',CO08:'Can Taste Be Owned in the Age of Generative AI?'};
for(const [id,title] of Object.entries(nextTitles)){const p=packages.find(x=>x.id===id);p.title=title;p.status='Evidence mapped';}
export const featured=['B01','CA02','CO01','CN04','B10','CA10','CO06','CO08'];
export const objects=[
{id:'83877',title:'Dress',maker:'French',date:'1735–40',accession:'1983.399.1',medium:'Silk, flax',credit:'Gift of Mary Tavener Holmes, 1983',image:'https://images.metmuseum.org/CRDImages/ci/web-large/DT7538.jpg',caption:'A garment record becomes institutional evidence when material, date, maker, identifier, and rights remain attached.',alt:'Eighteenth-century French silk dress with a fitted bodice and full skirt, from The Metropolitan Museum of Art collection.',url:'https://www.metmuseum.org/art/collection/search/83877',license:'Public Domain / Met Open Access'},
{id:'157996',title:'Afternoon dress',maker:'Jeanne Hallée',date:'ca. 1900',accession:'2009.300.3098a, b',medium:'Silk',credit:'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art; Gift of Marion Litchfield, 1950',image:'https://images.metmuseum.org/CRDImages/ci/web-large/50.72.1a-b_threequarter_front_CP4.jpg',caption:'A less-remembered house remains researchable because its object record survives.',alt:'Pale silk afternoon dress by Jeanne Hallée, shown from the front at a three-quarter angle.',url:'https://www.metmuseum.org/art/collection/search/157996',license:'Public Domain / Met Open Access'},
{id:'106420',title:'Dress',maker:'American or European',date:'ca. 1903',accession:'1976.258.13',medium:'Linen, cotton',credit:'Gift of Miss Eva Drexel Dahlgren, 1976',image:'https://images.metmuseum.org/CRDImages/ci/web-large/1976.258.13_F2.JPG',caption:'Construction evidence can outlive the operating house—but only if the physical object and record stay paired.',alt:'Light-colored linen and cotton dress dated around 1903, displayed frontally.',url:'https://www.metmuseum.org/art/collection/search/106420',license:'Public Domain / Met Open Access'},
{id:'81112',title:'Ball gown',maker:'House of Worth',date:'ca. 1872',accession:'46.25.1a–d',medium:'Silk',credit:'Gift of Mrs. Philip K. Rhinelander, 1946',image:'https://images.metmuseum.org/CRDImages/ci/web-large/DT426.jpg',caption:'The house is visible as both maker attribution and an enduring cataloguing unit.',alt:'Elaborately trimmed silk ball gown by the House of Worth, dated around 1872.',url:'https://www.metmuseum.org/art/collection/search/81112',license:'Public Domain / Met Open Access'}];
export const claims={B01:[['House is an operating condition, not an honorific.','INFERENCE',['S11','S16','S21']],['Bonnie Cashin described forming Bonnie Cashin, Inc.','VERIFIED',['S11']]],CA02:[['Tapestry reports that designers use product-design archives as a resource for concepts.','VERIFIED',['S35']],['An archive can function as active design infrastructure.','INFERENCE',['S21','S22','S35']]],CO01:[['Fashion creations may implicate distinct trademark, design, copyright, and patent systems.','VERIFIED',['S28','S29','S30']],['A personal name and the trademark bearing it are not necessarily controlled by the same party.','INFERENCE',['S28','S29']]],CN04:[['Preserving files without decision narration can lose institutional intelligence.','INFERENCE',['S08','S39']],['Personal digital archiving guidance supports inventory, description, storage, and preservation planning.','VERIFIED',['S08']]]};

export const exhibitions={
  B01:{
    kicker:'Threshold 01 · Person → practice → house',
    thesis:'A fashion house begins when taste stops being a private instinct and becomes a repeatable system other people can carry, question, record, and continue.',
    intro:['“House” sounds like prestige, but prestige is an effect—not an operating model. The useful threshold is whether the work can be recognized, produced, evidenced, and responsibly continued beyond one extraordinary act.','Bonnie Cashin’s oral-history record matters here because it keeps the founder’s account connected to an institutional record. The House of Worth gown matters differently: the maker survives in cataloguing as a house, while the object retains a date, accession number, material description, credit line, and physical presence. Together they show two sides of institutionalization: narrated formation and durable attribution.'],
    movements:[
      ['01 · CODE','Can the eye be explained?','A code is not a mood board. It is a set of recurring decisions—silhouette, proportion, material, finish, behavior, refusal—with examples, exceptions, and a reason for each. The test is not whether every object looks alike. It is whether a collaborator can recognize the governing judgment.','INFERENCE',['S11','S21']],
      ['02 · CARRY','Can another hand act without impersonating?','An institution needs roles, handoffs, review rituals, and vocabulary. Documentation should transmit the standard while leaving room for skilled interpretation. If every decision must return to the founder, the practice has staff but not institutional capacity.','PROPOSAL',['S11','S16']],
      ['03 · PROOF','Can the work prove its own making?','Collection records, samples, specifications, correspondence, credits, rights decisions, and accession-quality metadata turn memory into evidence. The record does not replace the object; it prevents the object from becoming anonymous.','INFERENCE',['S15','S21']],
      ['04 · CONTINUITY','Can the system survive absence?','A house is tested by illness, departure, conflict, growth, sale, and succession. Continuity requires named authority, access to accounts and files, an archive, and a method for distinguishing evolution from imitation.','PROPOSAL',['S39','S40']]
    ],
    tension:'Codifying taste can become a cage. The goal is not to freeze a signature look; it is to preserve how decisions are made—including how the house recognizes when its old answer is no longer enough.',
    fieldwork:['Write five decisions that recur across the work.','For each decision, attach one example and one deliberate exception.','Name the person, record, or ritual that carries it when the founder is absent.','Mark every answer that still exists only in the founder’s memory.'],
    objectId:'81112',
    objectUse:'House of Worth is catalogued as maker. The object record demonstrates how house-level attribution and object-level provenance can remain attached across generations.',
    outputs:['3,000-word canonical essay','Eight-minute visual essay treatment','Nine-frame “When does a designer become a house?” carousel','60-second threshold diagnostic','House Threshold interactive','Downloadable package brief and evidence register']
  },
  CA02:{
    kicker:'Transmission study · Archive → collaborator',
    thesis:'An archive becomes institutional infrastructure when it is retrievable, interpretable, rights-aware, and capable of changing a live creative decision.',
    intro:['A room full of garments is not automatically an archive, and an archive is not automatically useful. The institution begins when objects and records can answer a new question without severing evidence from interpretation.','Tapestry’s public filing states that designers use product-design archives as a resource for concepts. The Gianfranco Ferré Research Center presents another model: an archive organized for research and transmission. Neither source proves that every archive produces good design. They establish a narrower point—the archive can be deliberately operated as creative infrastructure.'],
    movements:[
      ['01 · RETRIEVE','Can the right record be found?','Identifiers, dates, makers, materials, controlled vocabulary, file relationships, and search pathways determine whether memory is available at the moment of decision.','VERIFIED',['S21','S35']],
      ['02 · READ','Can someone understand why it matters?','A sketch, fitting note, failed sample, or garment becomes more useful when the record preserves the question it answered—not only what it looks like.','INFERENCE',['S21','S22']],
      ['03 · TRANSFORM','Can the archive generate difference?','The strongest use is not literal revival. It is recovery of a method, constraint, construction problem, or unresolved question that can be recomposed for a new context.','PROPOSAL',['S21','S22']],
      ['04 · CITE','Can the new work show its lineage?','Source identifiers, rights decisions, credits, and transformation notes let inspiration remain accountable. Citation does not weaken originality; it distinguishes research from extraction.','PROPOSAL',['S23','S24']]
    ],
    tension:'An archive can consolidate authority as easily as it distributes knowledge. Who receives access, who describes the objects, and whose labor appears in the metadata determines what the institution can remember.',
    fieldwork:['Select one current design question—not a favorite old object.','Retrieve three records that answer it in different ways.','Record the evidentiary fact and your interpretation in separate fields.','Define what may be reused, what may only be linked, and what requires permission.'],
    objectId:'157996',
    objectUse:'Jeanne Hallée’s afternoon dress makes a quieter institutional point: a house can remain researchable after public memory fades when maker, date, materials, accession, credit, and image rights survive together.',
    outputs:['Canonical archive-as-employee essay','Four-movement scroll narrative','Six-part archive literacy short series','Archive Activation interactive','Metadata and rights worksheet','Downloadable package brief and evidence register']
  },
  CO01:{
    kicker:'Control study · Identity → registrable assets',
    thesis:'Your name can be your identity, your reputation, a trademark, a company asset, a domain, a social handle, and an archive authority—and those forms of control do not automatically travel together.',
    intro:['The label may bear a founder’s name while contracts, registrations, accounts, voting arrangements, or a later transaction place key forms of control elsewhere. “It is my name” is therefore the beginning of an inventory, not the end of the analysis.','WIPO distinguishes the intellectual-property tools that may operate around fashion, including trademarks and industrial designs; its fashion diagnostic is an educational starting point rather than a legal conclusion. The useful editorial move is to separate the asset layers, identify the evidence for each, and mark where qualified counsel must replace inference.'],
    movements:[
      ['01 · NAME','Which identity is being used?','List the personal name, legal entity names, label names, collection marks, monograms, product names, likeness, signatures, and recurring verbal identifiers separately.','PROPOSAL',['S28','S29']],
      ['02 · CHANNEL','Where does the public encounter it?','Domains, storefronts, social handles, marketplaces, mailing lists, apps, authentication systems, and press accounts each have different administrators and recovery paths.','PROPOSAL',['S29','S32']],
      ['03 · RIGHT','What kind of control is claimed?','Trademark, copyright, industrial-design protection, patent, contract, publicity or personality rights, corporate control, and platform access answer different questions. One cannot be substituted casually for another.','VERIFIED',['S28','S30','S31']],
      ['04 · EVIDENCE','What record would prove it?','Registration records, assignments, licenses, operating agreements, access logs, vendor accounts, and executed contracts belong in a control map with owner, territory, term, renewal, and review fields.','PROPOSAL',['S29','S32']]
    ],
    tension:'This exhibition is an issue-spotting tool, not legal advice. Public databases can reveal registrations and recorded assignments, but they do not necessarily establish every contractual, common-law, territorial, or beneficial interest.',
    fieldwork:['Inventory every public-facing form of the founder or house name.','Record the legal or account owner for each—never infer from the display name.','Add territory, class or category, term, renewal date, administrator, and recovery path.','Send unresolved ownership or licensing questions to qualified counsel.'],
    objectId:'83877',
    objectUse:'The eighteenth-century French dress is deliberately attributed only as “French.” It demonstrates the opposite of name control: a richly documented object can survive while individual authorship and institutional identity remain unavailable.',
    outputs:['Canonical name-control essay','Identity-asset system map','Five issue-spotting shorts','Name Control interactive','Counsel-preparation worksheet','Downloadable package brief and evidence register']
  },
  CN04:{
    kicker:'Continuity study · Living memory → durable record',
    thesis:'The best moment to begin an archive is while the founder can still explain why a decision was made, what failed, who carried it, and what should never be repeated.',
    intro:['Estate planning asks what should happen after incapacity or death. A living archive begins earlier and answers a different operational question: what knowledge must be captured before silence makes the record ambiguous?','National Archives guidance emphasizes requirements for managing electronic records. Smithsonian preservation resources distinguish collections care, storage, handling, and textile-conservation needs. These sources do not supply a bespoke succession plan; they establish practical preservation disciplines that a fashion practice can adapt with professional advice.'],
    movements:[
      ['DAY 01 · INVENTORY','Name what exists.','Create identifiers for garments, samples, sketches, patterns, specifications, correspondence, photographs, recordings, contracts, accounts, and born-digital files.','VERIFIED',['S08','S39']],
      ['DAY 02 · PAIR','Reconnect object and file.','Pair physical location with filenames, versions, photographs, condition notes, creator credits, and related agreements so neither half becomes orphaned.','PROPOSAL',['S39','S40']],
      ['DAY 03 · NARRATE','Capture the decision voice.','Record short founder and collaborator accounts: the problem, alternatives, refusal, compromise, failure, and what changed afterward. Preserve transcripts with the recording.','INFERENCE',['S08','S39']],
      ['DAY 04–07 · STEWARD','Protect access and future meaning.','Document formats, backups, storage conditions, privacy, rights, account recovery, successor access, conservation referrals, and a schedule for reviewing the archive.','VERIFIED',['S40','S41','S42','S43']]
    ],
    tension:'Preservation is selective power. A founder-centered archive can erase the patternmaker, sewer, model, photographer, assistant, client, and community knowledge that carried the institution. The archive plan must ask who is missing and who may describe the work.',
    fieldwork:['Choose one garment and assign a persistent internal identifier.','Pair it with every related physical and digital record.','Record a five-minute account from the founder and one collaborator.','Document rights, privacy, storage, backup, access, and professional-referral needs.'],
    objectId:'106420',
    objectUse:'The linen-and-cotton dress survives with material, approximate date, accession, donor credit, and photography. The pairing shows what an object record can preserve—and how much decision context may still be absent.',
    outputs:['3,000-word living-archive guide','Seven-day email sequence','Founder and collaborator audio prompts','Living Archive interactive','Physical/digital pairing register','Downloadable package brief and evidence register']
  }
};

Object.assign(claims,{
  B10:[['Public recognition is not the same thing as a durable operating system.','INFERENCE',['S11','S15','S33']],['A documented practice can preserve roles, decisions, and evidence beyond publicity.','PROPOSAL',['S08','S39']]],
  CA10:[['Fashion archives preserve evidence of many hands even when public storytelling centers one name.','INFERENCE',['S15','S16','S17']],['Credit and role records are institutional infrastructure, not ornamental acknowledgments.','PROPOSAL',['S10','S15']]],
  CO06:[['A platform account is governed by platform access and recovery systems, not possession of the audience itself.','INFERENCE',['S32','S36']],['An owned contact channel and exportable records reduce—but do not eliminate—platform dependency.','PROPOSAL',['S08','S39']]],
  CO08:[['Copyright, trademark, design protection, and contract answer different questions about creative work.','VERIFIED',['S28','S29','S30','S31']],['Aesthetic resemblance alone does not determine a legal claim.','INFERENCE',['S28','S30']]]
});

Object.assign(exhibitions,{
  B10:{
    kicker:'Foundation study · Visibility → capacity',
    thesis:'A personal brand makes a person recognizable. An institution makes their judgment, relationships, records, rights, and work capable of operating beyond constant personal performance.',
    intro:['A personal brand can be powerful: a recognizable voice, a face, a promise, and a route through crowded attention. But recognition is not infrastructure. An institution begins where public identity is joined to repeatable decisions, accountable roles, retrievable evidence, controlled assets, and a method for continuing when the founder is unavailable.','The distinction matters in fashion because the public often encounters a name before it encounters the atelier, contracts, archive, production network, or governance behind it. FIT oral histories and archival finding aids preserve precisely the layers publicity tends to compress: formation, collaborators, operating choices, and records. This exhibition treats brand as an interface and institution as the system beneath it.'],
    movements:[
      ['01 · SIGNAL','What does the public recognize?','Identify the repeated promise, visual language, subject, and point of view that make the person legible. These signals matter, but they are evidence of recognition—not proof that the work can be produced, governed, or continued.','INFERENCE',['S11','S13']],
      ['02 · SYSTEM','What repeats without performance?','Map how research becomes a brief, how decisions are approved, how work is produced, and how quality is reviewed. A system must be inspectable enough to improve and flexible enough to accommodate judgment.','PROPOSAL',['S08','S39']],
      ['03 · ASSET','What remains under accountable control?','Separate reputation from the name, entity, marks, domains, mailing list, contracts, files, samples, and archive. The public may perceive one identity while ownership and access are fragmented across many records.','PROPOSAL',['S28','S32']],
      ['04 · ABSENCE','What happens when the founder is offline?','Run a seventy-two-hour absence test. Can collaborators find current files, communicate with clients, fulfill obligations, protect accounts, and identify who may decide? The gaps reveal where a brand still depends on continuous personal availability.','PROPOSAL',['S08','S39']]
    ],
    tension:'Institutionalization can turn a living voice into bureaucracy. The aim is not to make the person interchangeable; it is to protect the conditions that let singular judgment remain singular without making exhaustion the operating model.',
    fieldwork:['Write the public promise in one sentence.','Name the repeatable system that fulfills that promise.','List the controlled record or asset supporting each step.','Run the seventy-two-hour founder-absence test.'],
    objectId:'81112',objectUse:'The House of Worth object record separates recognizable house attribution from the durable cataloguing apparatus that lets the attribution remain useful generations later.',
    outputs:['Canonical essay: Brand Is the Door, Not the House','Eight-minute visual essay script','Nine-frame brand-versus-institution carousel','Three 45-second social scripts','Brand / Institution Gap Audit','Newsletter and LinkedIn editions'],
    platform:['LONG — Open on a founder posting from a fitting room; move beneath the image into roles, records, assets, and an absence test. Close: build a system that protects the eye, not a machine that replaces it.','SHORT 01 — Hook: If your business stops when you stop posting, you have recognition—not yet an institution. Demonstrate the four-layer test in 45 seconds.','SHORT 02 — Show one name splitting into five records: mark, domain, list, archive, agreement. End with the question: which one do you actually control?','CAROUSEL — Nine frames: signal; system; asset; authority; archive; access; absence; gap; first repair.','NEWSLETTER — A 1,200-word field edition with the complete 72-hour test and a downloadable audit.','LINKEDIN — Lead with the operating distinction, give one fashion example, and invite readers to name the task that cannot move without them.']
  },
  CA10:{
    kicker:'Credit study · Signature → constellation',
    thesis:'The lone fashion genius is a useful publicity device and a poor description of how collections acquire form, finish, circulation, and memory.',
    intro:['A collection may be signed by one name, but it is carried through pattern cutting, textile development, sampling, fitting, casting, styling, production, photography, distribution, conservation, and criticism. The problem is not that a creative director has no singular role. The problem is that singular authority is too often narrated as solitary making.','Institutional archives complicate that story. Finding aids, oral histories, accession records, credits, and production documents can reconnect work to the people and relationships that made it possible. This exhibition asks readers to treat credit as operational evidence: a record of who held which knowledge, who made which decision, and where the institution would fracture if that contribution disappeared.'],
    movements:[
      ['01 · SIGNATURE','Why does one name dominate?','A single name gives press, commerce, and memory a compact handle. It can truthfully identify creative authority while still concealing the distributed labor required to materialize that authority.','INFERENCE',['S11','S12','S13']],
      ['02 · CONSTELLATION','Who translated the idea?','Build a role map from concept to archive. Record not only names but decisions: who interpreted proportion, solved construction, negotiated feasibility, shaped the image, and preserved the evidence.','PROPOSAL',['S15','S16','S17']],
      ['03 · CREDIT','What should the record retain?','Credits should travel with garments, images, video, collection notes, and archival deposits. The durable record needs consistent role language and a correction path when work is omitted or misdescribed.','PROPOSAL',['S10','S15']],
      ['04 · POWER','Does visibility follow value?','Credit cannot by itself repair inequitable pay, ownership, or authority. It does, however, make labor and decision structures more legible—creating evidence for harder questions about compensation and control.','INFERENCE',['S10','S15']]
    ],
    tension:'Replacing one heroic story with an indiscriminate list can flatten responsibility. A useful credit system distinguishes creative authority, execution, approval, contribution, and ownership rather than pretending every role is identical.',
    fieldwork:['Choose one finished look.','Trace every decision and hand from research to publication.','Attach a name and role to each decision where consent permits.','Record missing, disputed, or uncredited labor as unresolved.'],
    objectId:'157996',objectUse:'The Jeanne Hallée dress retains a maker name while the record also preserves institution, donor, materials, date, accession, and photography—an entry point into the broader constellation behind survival.',
    outputs:['Canonical essay: The Signature and the Constellation','Ten-minute narrated credit-map script','Seven-role carousel','Four collaborator-credit shorts','Constellation Mapper','Interview, newsletter, and classroom editions'],
    platform:['LONG — Follow one look backward from museum record to the absent production floor; distinguish creative authority from solitary manufacture.','SHORT 01 — A rapid roll call of the decisions hidden inside “designed by.”','SHORT 02 — Ask: if this person vanished from the record, what knowledge would the house lose?','CAROUSEL — Seven role plates with a decision, evidence field, and credit verb on each.','AUDIO — A six-question collaborator oral-history prompt with consent and correction language.','CLASSROOM — Map one object without inventing missing names; label the gaps as part of the evidence.']
  },
  CO06:{
    kicker:'Platform study · Reach → dependency',
    thesis:'A million followers can create extraordinary reach while remaining a rented route to people—subject to platform rules, access loss, algorithmic distribution, and incomplete portability.',
    intro:['Follower count is a visible measure inside a platform. It is not a deed to an audience, a complete customer record, or a guaranteed line of communication. Creators and fashion founders often build real cultural and economic value on accounts whose administration, recovery, distribution, and export are governed elsewhere.','The practical response is not to abandon platforms. It is to treat them as powerful channels inside a broader institutional architecture: an owned domain, consented contact records, documented account authority, retrievable content, customer records where lawfully held, and a tested recovery plan. “Rented” is an operating metaphor here, not a legal classification of every platform relationship.'],
    movements:[
      ['01 · REACH','What can the platform do exceptionally well?','Discovery, social proof, conversation, cultural participation, and rapid distribution are real institutional advantages. The audit begins by naming that value rather than treating dependency as failure.','INFERENCE',['S33','S36']],
      ['02 · ACCESS','Who can enter and recover the account?','Record the account owner, administrators, authentication method, recovery contacts, device access, and escalation route. A display name or founder face does not prove operational control.','PROPOSAL',['S08','S39']],
      ['03 · PORTABILITY','What can leave with consent and context?','Map content originals, captions, contacts, customer records, permissions, analytics exports, and conversation history. Preserve only what may lawfully and ethically be retained.','PROPOSAL',['S08','S39']],
      ['04 · ROUTE','How many ways can the institution reach people?','Build at least one controlled destination and one consent-based contact route. Redundancy should improve continuity without manipulating audiences or copying data beyond its stated purpose.','PROPOSAL',['S08','S39']]
    ],
    tension:'Calling platforms “rented” can understate the communities, creativity, and livelihoods built there. The argument is narrower: meaningful participation and asset control are different institutional questions, and both deserve deliberate design.',
    fieldwork:['List every platform and its actual owner or administrator.','Test recovery without relying on one person or device.','Inventory exportable content and consented contact routes.','Create a continuity notice that does not pressure people to migrate.'],
    objectId:'106420',objectUse:'This dress survives through an institutional record rather than a volatile feed. Its persistent identifier, materials, date, credit, and canonical source model the kind of context platform posts often lose.',
    outputs:['Canonical essay: A Million Followers Is a Rented Institution','Six-minute platform-dependency film script','Eight-frame reach-versus-control carousel','Three account-continuity shorts','Audience Portability Map','Newsletter, LinkedIn, and workshop editions'],
    platform:['LONG — Begin with a seven-digit counter; remove it layer by layer until only access, records, permissions, and routes remain.','SHORT 01 — Followers are reach. They are not automatically contact permission, customer records, or recovery control.','SHORT 02 — The five-minute account continuity drill: owner, admin, recovery, originals, alternate route.','CAROUSEL — Reach; access; data; permission; archive; route; recovery; next action.','WORKSHOP — Complete the portability map without downloading or repurposing personal data beyond consent.','NEWSLETTER — Pair the argument with an account-recovery checklist and a plain-language privacy note.']
  },
  CO08:{
    kicker:'Authorship study · Influence → evidence',
    thesis:'Taste can be recognized, taught, imitated, and commercially valuable without becoming a single ownable legal object; generative AI makes the need to separate those categories urgent.',
    intro:['“Taste” bundles together judgment, selection, arrangement, references, recurring codes, reputation, and the ability to decide what does not belong. Some outputs, names, designs, agreements, and confidential materials may engage specific legal regimes. An aesthetic resemblance or prompt that invokes a style does not by itself answer which right—if any—has been implicated.','WIPO’s fashion resources distinguish trademarks, designs, copyright, and patents as different tools with different subject matter. That is the beginning of the analysis, not a verdict on a particular model, dataset, output, jurisdiction, or dispute. This exhibition offers an evidence architecture: document sources, human decisions, permissions, transformations, claims, and uncertainty before reaching for the word ownership.'],
    movements:[
      ['01 · TASTE','What exactly is being claimed?','Separate a general sensibility from a named mark, protected work, registered design, confidential process, contractual promise, or misleading commercial representation. Precision prevents cultural grievance from being mistaken for a settled legal result.','VERIFIED',['S28','S30','S31']],
      ['02 · TRACE','What entered the process?','Keep a source log for references, licensed assets, model and tool versions, prompts, human selections, rejected outputs, edits, and final approvals. The record supports accountability without proving a legal conclusion on its own.','PROPOSAL',['S08','S39']],
      ['03 · TRANSFORM','Where is human judgment visible?','Describe the problem, constraints, alternatives, selection criteria, arrangement, revision, and final expressive choices. Avoid claiming that effort alone creates protection; the purpose is to preserve an accurate creative record.','PROPOSAL',['S28','S29']],
      ['04 · REVIEW','Which question needs counsel or permission?','Flag identifiable source works, living artists or houses named in prompts, confidential inputs, deceptive attribution, commercial marks, uncertain licenses, and jurisdiction-specific design questions for qualified review.','PROPOSAL',['S28','S29','S30']]
    ],
    tension:'Documentation can become performative transparency, and legal categories cannot resolve every ethical question about extraction, cultural authority, labor, or consent. A responsible process needs both legal review and editorial judgment.',
    fieldwork:['Define the element you are calling taste.','Separate facts, influences, protected assets, and interpretations.','Record inputs, permissions, human decisions, and transformations.','Send unresolved rights or attribution questions to qualified counsel.'],
    objectId:'83877',objectUse:'The maker of this richly documented dress remains identified only as French. The object demonstrates how evidence can preserve material facts while authorship and institutional identity remain unresolved.',
    outputs:['Canonical essay: Can Taste Be Owned?','Twelve-minute evidence-led video script','Ten-frame rights-versus-resemblance carousel','Five AI authorship shorts','Taste Trace Ledger','Newsletter, seminar, and counsel-prep editions'],
    platform:['LONG — Move from the seductive sentence “they stole my taste” to seven narrower questions evidence can actually answer.','SHORT 01 — Style, trademark, copyrighted work, design right, contract, and attribution are not synonyms.','SHORT 02 — Show the trace ledger: source; permission; prompt; selection; edit; approval; unresolved issue.','CAROUSEL — Ten distinctions, each with “what it can show” and “what it cannot decide.”','SEMINAR — Compare one historical reference chain and one generative workflow without reproducing disputed source material.','COUNSEL PREP — Package exact assets, territories, dates, agreements, uses, and desired remedies; do not arrive with only screenshots and conclusions.']
  }
});
