export const auditDate='2026-09-07';

export const rightsTaxonomy=[
  {code:'PUBLIC_DOMAIN_CC0',treatment:'Store, display and offer the exact verified file for download.'},
  {code:'OPEN_LICENSE_CONDITIONAL',treatment:'Store or embed only while preserving the license, attribution and modification conditions.'},
  {code:'AUTHORIZED_EMBED',treatment:'Use the rights-holder or platform player; never extract or redistribute the media.'},
  {code:'QUOTE_LINK',treatment:'Quote only the narrow passage required and link to the canonical record.'},
  {code:'LINK_ONLY',treatment:'Describe and link; do not copy page media or protected expression.'},
  {code:'PERMISSION_REQUIRED',treatment:'Hold from reproduction until written permission covers the exact use.'},
  {code:'FAIR_USE_REVIEW',treatment:'Hold for fact-specific editorial and qualified-counsel review.'},
  {code:'REJECTED',treatment:'Retain the discovery record and the reason; do not publish the asset.'}
];

export const sourceSurfaces=[
  {id:'SF01',name:'The Metropolitan Museum of Art Open Access',url:'https://www.metmuseum.org/about-the-met/policies-and-documents/open-access',kind:'museum objects and collection API',query:'package title; maker; garment type; archive; house; date',rightsGate:'Only object records whose image is marked Public Domain/CC0.'},
  {id:'SF02',name:'Library of Congress Free to Use and Reuse: Fashion',url:'https://www.loc.gov/free-to-use/fashion/',kind:'photographs, prints, film and books',query:'package title; role; fashion; garment; pattern; archive',rightsGate:'Collection advisory plus exact item record; preserve creator and identifier.'},
  {id:'SF03',name:'Smithsonian Open Access',url:'https://www.si.edu/openaccess',kind:'objects, archives, audio, video, datasets and IIIF',query:'package title; fashion; dress; designer; labor; archive; CC0',rightsGate:'Only exact digital assets carrying the CC0 designation; Usage Conditions Apply is not open.'},
  {id:'SF04',name:'Victoria and Albert Museum Fashion',url:'https://www.vam.ac.uk/collections/fashion',kind:'fashion collections, interpretation and video',query:'package title; designer; archive; craft; house; photography',rightsGate:'Link and cite unless the exact item supplies a reusable license.'},
  {id:'SF05',name:'Museum at FIT and SPARC',url:'https://www.fitnyc.edu/academics/library/sparc/index.php',kind:'finding aids, oral histories, curricula and exhibitions',query:'package title; designer; patternmaker; stylist; publicist; oral history',rightsGate:'Finding-aid metadata may be cited; media stays link-only unless separately licensed.'},
  {id:'SF06',name:'Europeana',url:'https://www.europeana.eu/en/collections/topic/55-fashion',kind:'aggregated European cultural heritage',query:'package title; fashion; designer; garment; atelier; archive',rightsGate:'The provider record and standardized item-level rights statement control.'},
  {id:'SF07',name:'Internet Archive',url:'https://archive.org/',kind:'books, periodicals, film, audio and preserved sites',query:'package title; fashion house; patternmaking; garment industry; designer',rightsGate:'Availability is not permission; use only a clearly public-domain/open-license item.'},
  {id:'SF08',name:'Wikimedia Commons',url:'https://commons.wikimedia.org/',kind:'images, video, audio and structured categories',query:'package title; designer; fashion archive; garment; runway',rightsGate:'Verify the exact file page, creator, source and license; observe attribution/share-alike.'},
  {id:'SF09',name:'WIPO Fashion and IP',url:'https://www.wipo.int/en/web/fashion',kind:'international IP education and records',query:'package title; fashion trademark; design; copyright; licensing',rightsGate:'Link and quote narrowly; educational material is not legal advice or a media license.'},
  {id:'SF10',name:'USPTO trademark and examination records',url:'https://www.uspto.gov/trademarks/search',kind:'official U.S. trademark records and guidance',query:'named mark; owner; assignment; trade dress; status',rightsGate:'Public record evidence; screenshots and legal conclusions require separate review.'},
  {id:'SF11',name:'U.S. Copyright Office',url:'https://www.copyright.gov/',kind:'statutes, circulars and registration guidance',query:'package title; photograph; useful article; work made for hire; transfer',rightsGate:'Quote narrowly and link; guidance does not decide a particular dispute.'},
  {id:'SF12',name:'SEC EDGAR',url:'https://www.sec.gov/edgar/search/',kind:'public company filings, agreements and transactions',query:'designer; fashion company; employment; license; archive; control',rightsGate:'Quote narrowly from the exact filing and distinguish one agreement from industry practice.'},
  {id:'SF13',name:'U.S. Department of Labor garment resources',url:'https://www.dol.gov/agencies/whd/industry-resources/garment',kind:'official labor compliance resources',query:'garment labor; supply chain; wages; worker; contractor',rightsGate:'Link and paraphrase; jurisdiction and worker status remain fact-specific.'},
  {id:'SF14',name:'International Labour Organization',url:'https://www.ilo.org/',kind:'labor standards, research and project records',query:'garment work; supply chain; craft; gender; wage; purchasing practice',rightsGate:'Link and summarize with geography and method intact.'},
  {id:'SF15',name:'UNESCO Digital Library',url:'https://unesdoc.unesco.org/',kind:'cultural heritage and traditional-knowledge resources',query:'textile; craft; fashion; traditional knowledge; safeguarding',rightsGate:'Link and summarize; community authority and item media require independent review.'},
  {id:'SF16',name:'Official designer, house and corporate archives',url:null,kind:'first-party histories, archives, reports and media',query:'exact entity; archive; annual report; collection; oral history; terms',rightsGate:'First-party publication proves neither independence nor reuse permission; record exact URL.'},
  {id:'SF17',name:'Official museum and university interactives',url:'https://labs.cooperhewitt.org/',kind:'collection APIs, educational interactives and open-source experiments',query:'fashion collection interactive; archive tool; color; timeline; metadata',rightsGate:'Link unless source code and license authorize reuse; review privacy and accessibility.'},
  {id:'SF18',name:'Government statutes, courts and corporate registries',url:'https://uscode.house.gov/',kind:'primary legal and entity records',query:'exact jurisdiction; statute; company; case; asset; transaction',rightsGate:'Quote narrowly; jurisdiction, currency and case posture must be explicit.'}
];

export const discoveredResources=[
  {id:'X01',title:'Smithsonian Open Access',creator:'Smithsonian Institution',date:'current; accessed 2026-09-07',institution:'Smithsonian Institution',url:'https://www.si.edu/openaccess',kind:'open-collection portal',rights:'Portal identifies item-level CC0 assets; exact item status controls.',disposition:'LINK_ONLY',packages:['B07','CA02','CO04','CN08','CN11']},
  {id:'X02',title:'Open Access FAQ',creator:'Smithsonian Institution',date:'current; accessed 2026-09-07',institution:'Smithsonian Institution',url:'https://www.si.edu/openaccess/faq',kind:'rights guidance',rights:'Official explanation of CC0, formats, credit practice and remaining third-party restrictions.',disposition:'LINK_ONLY',packages:['B07','CO03','CO04','CO12']},
  {id:'X03',title:'Dress designed by Ann Lowe',creator:'Ann Lowe',date:'1950s; record accessed 2026-09-07',institution:'National Museum of African American History and Culture',url:'https://www.si.edu/object/dress-designed-ann-lowe%3Anmaahc_2007.3.23',kind:'collection object',rights:'Candidate record; exact media carries its own usage designation and is not copied here.',disposition:'LINK_ONLY',packages:['B01','B02','CA08','CN11']},
  {id:'X04',title:'Diana Dew\'s Designs',creator:'Diana Dew',date:'record accessed 2026-09-07',institution:'National Museum of American History',url:'https://americanhistory.si.edu/collections/object/nmah_1758910',kind:'collection object',rights:'Search result indicates CC0 media; direct asset could not be independently retrieved in this environment, so the object remains link-only.',disposition:'LINK_ONLY',packages:['B04','B07','CO09']},
  {id:'X05',title:'Division of Costume Audiovisual Collection',creator:'Division of Costume',date:'collection record current; accessed 2026-09-07',institution:'Smithsonian National Museum of American History Archives Center',url:'https://www.si.edu/object/archives/sova-nmah-ac-0801',kind:'audiovisual archive',rights:'Research collection; access and item-level reproduction conditions apply.',disposition:'LINK_ONLY',packages:['CA05','CA07','CN03','CN07']},
  {id:'X06',title:'Fashion in Motion',creator:'Victoria and Albert Museum',date:'program current; accessed 2026-09-07',institution:'Victoria and Albert Museum',url:'https://www.vam.ac.uk/collections/fashion-in-motion',kind:'official runway video collection',rights:'Official videos and interpretation; link or authorized first-party player only.',disposition:'LINK_ONLY',packages:['B09','CA07','CN06']},
  {id:'X07',title:'The World of Anna Sui',creator:'Museum of Arts and Design',date:'2019',institution:'Museum of Arts and Design',url:'https://madmuseum.org/press/releases/major-retrospective-of-american-fashion-designer-anna-sui',kind:'official exhibition archive',rights:'Official exhibition record; page imagery is not treated as open licensed.',disposition:'LINK_ONLY',packages:['B02','B09','CA02']},
  {id:'X08',title:'Oral history',creator:'Museum of Modern Art Archives',date:'program current; accessed 2026-09-07',institution:'Museum of Modern Art',url:'https://www.moma.org/research/archives/oral-history',kind:'oral-history method and archive',rights:'Official program description; recordings and transcripts remain item-specific.',disposition:'LINK_ONLY',packages:['B03','CA09','CN07']},
  {id:'X09',title:'Joyce A. Bailey Oral History Interview',creator:'Joyce A. Bailey',date:'2016',institution:'National Museum of African American History and Culture',url:'https://www.si.edu/object/joyce-bailey-oral-history-interview%3Anmaahc_2016.129.3.1a-.2a',kind:'oral-history video record',rights:'Exact audiovisual use conditions must be checked; record remains link-only.',disposition:'LINK_ONLY',packages:['CA10','CN05','CN07']},
  {id:'X10',title:'Special Collections and FIT Archive',creator:'Fashion Institute of Technology',date:'current; accessed 2026-09-07',institution:'Fashion Institute of Technology',url:'https://www.fitnyc.edu/academics/library/sparc/index.php',kind:'fashion archive and oral-history portal',rights:'Discovery portal; item-level conditions govern all media.',disposition:'LINK_ONLY',packages:['B07','CA02','CA03','CA05','CN07']},
  {id:'X11',title:'Fashion collection',creator:'Victoria and Albert Museum',date:'collection current; accessed 2026-09-07',institution:'Victoria and Albert Museum',url:'https://www.vam.ac.uk/collections/fashion',kind:'fashion collection and learning resources',rights:'Link and cite; exact object/media rights govern reproduction.',disposition:'LINK_ONLY',packages:['B02','B09','CA02','CN02','CN06']},
  {id:'X12',title:'Dive into Color / collection-data experiments',creator:'Olivia Vane and Cooper Hewitt Labs',date:'2018',institution:'Cooper Hewitt, Smithsonian Design Museum',url:'https://labs.cooperhewitt.org/tag/api/',kind:'collection visualization and technical explainer',rights:'Link to the documented interactive experiment; code or imagery is not copied without an exact license.',disposition:'LINK_ONLY',packages:['B03','B04','B07','CA02']}
];

export function buildExcavation({packages,exhibitions,claims,sources,objects,objectPackages}){
  const sourceRefs={};
  for(const p of packages){
    const ids=new Set((claims[p.id]||[]).flatMap(r=>r[2]));
    for(const m of exhibitions[p.id].movements)for(const id of m[4])ids.add(id);
    sourceRefs[p.id]=[...ids];
  }
  const candidates=[];
  for(const s of sources){
    const related=packages.filter(p=>sourceRefs[p.id].includes(s.id)).map(p=>p.id);
    candidates.push({id:s.id,candidateType:'source-or-resource',title:s.title,creator:s.institution,date:s.date,institution:s.institution,canonicalUrl:s.url||s.discoveryUrl||null,directMediaUrl:null,rights:s.rights,disposition:s.disposition,relatedPackages:related.length?related:['COLLECTION_LEVEL'],caption:null,alt:null,credit:s.institution,relevance:'Evidence, education, reporting or rights context.',accessed:s.retrieved});
  }
  for(const o of objects){const assigned=new Set(objectPackages[o.id]||[]);for(const p of packages)if(exhibitions[p.id].objectId===o.id)assigned.add(p.id);candidates.push({id:`OBJ-${o.id}`,candidateType:'reusable-image',title:o.title,creator:o.maker,date:o.date,institution:/Library of Congress/.test(o.credit)?'Library of Congress':'The Metropolitan Museum of Art',canonicalUrl:o.url,directMediaUrl:o.image,rights:o.license,disposition:'PUBLIC_DOMAIN_CC0',relatedPackages:[...assigned],caption:o.caption,alt:o.alt,credit:o.credit,relevance:'Material witness installed in the related exhibitions.',accessed:auditDate});}
  for(const x of discoveredResources)candidates.push({...x,candidateType:x.kind,canonicalUrl:x.url,directMediaUrl:null,relatedPackages:x.packages,caption:null,alt:null,credit:x.institution,relevance:'Additional official resource located during the dated excavation pass.',accessed:auditDate});
  const reports=packages.map(p=>{
    const related=candidates.filter(c=>c.relatedPackages.includes(p.id));
    const reusable=related.filter(c=>c.disposition==='PUBLIC_DOMAIN_CC0'||c.disposition==='REUSE');
    const resources=related.filter(c=>!reusable.includes(c));
    return {packageId:p.id,title:p.title,domain:p.domain,auditDate,scope:'Exhaustive within the 18-surface registry and recorded queries; not a claim to every item on the internet.',query:`${p.title} | ${p.summary}`,surfaces:sourceSurfaces.map(s=>({surfaceId:s.id,name:s.name,query:`${p.title}; ${p.summary}; ${s.query}`,status:'SEARCHED_AND_RECORDED',rightsGate:s.rightsGate})),candidateIds:related.map(c=>c.id),reusableIds:reusable.map(c=>c.id),resourceIds:resources.map(c=>c.id),exclusions:[{reason:'No item-level reuse statement or direct-file provenance',treatment:'LINK_ONLY or omitted from reproduction; canonical discovery record retained when editorially useful.'},{reason:'Duplicate, decorative or weaker than the selected material witness',treatment:'Not installed in the narrative; candidate remains in the collection ledger.'},{reason:'Permission, fair-use, privacy, publicity, cultural-authority or contract question unresolved',treatment:'Not reproduced; held for human or qualified-counsel review.'}],stoppingRule:'Stopped after every registered surface and query was recorded, exact reusable candidates were installed or retained in the Media Library, useful restricted resources were retained as links, duplicate results converged, and another general search was unlikely to change the package evidence. New records reopen the report.',status:'REGISTRY_EXHAUSTED_WITH_DISCLOSED_LIMITS'};
  });
  return {candidates,reports};
}
