export const auditDate='2026-09-07';

export const rightsTaxonomy=[
  {code:'PUBLIC_DOMAIN_CC0',treatment:'Store, display and offer the exact verified file for download.'},
  {code:'OPEN_LICENSE_CONDITIONAL',treatment:'Store or embed only while preserving the license, attribution and modification conditions.'},
  {code:'AUTHORIZED_EMBED',treatment:'Use the rights-holder or platform player; never extract or redistribute the media.'},
  {code:'QUOTE_LINK',treatment:'Quote only the narrow passage required and link to the canonical record.'},
  {code:'LINK_ONLY',treatment:'Describe and link; do not copy page media or protected expression.'},
  {code:'PERMISSION_REQUIRED',treatment:'Hold from reproduction until written permission covers the exact use.'},
  {code:'FAIR_USE_REVIEW',treatment:'Hold for fact-specific editorial and qualified-counsel review.'},
  {code:'REJECTED',treatment:'Retain the discovery record and the reason; do not publish the asset.'}
];

export const sourceSurfaces=[
  {id:'SF01',name:'The Metropolitan Museum of Art Open Access',url:'https://www.metmuseum.org/about-the-met/policies-and-documents/open-access',kind:'museum objects and collection API',query:'package title; maker; garment type; archive; house; date',rightsGate:'Only object records whose image is marked Public Domain/CC0.'},
  {id:'SF02',name:'Library of Congress Free to Use and Reuse: Fashion',url:'https://www.loc.gov/free-to-use/fashion/',kind:'photographs, prints, film and books',query:'package title; role; fashion; garment; pattern; archive',rightsGate:'Collection advisory plus exact item record; preserve creator and identifier.'},
  {id:'SF03',name:'Smithsonian Open Access',url:'https://www.si.edu/openaccess',kind:'objects, archives, audio, video, datasets and IIIF',query:'package title; fashion; dress; designer; labor; archive; CC0',rightsGate:'Only exact digital assets carrying the CC0 designation; Usage Conditions Apply is not open.'},
  {id:'SF04',name:'Victoria and Albert Museum Fashion',url:'https://www.vam.ac.uk/collections/fashion',kind:'fashion collections, interpretation and video',query:'package title; designer; archive; craft; house; photography',rightsGate:'Link and cite unless the exact item supplies a reusable license.'},
  {id:'SF05',name:'Museum at FIT and SPARC',url:'https://www.fitnyc.edu/academics/library/sparc/index.php',kind:'finding aids, oral histories, curricula and exhibitions',query:'package title; designer; patternmaker; stylist; publicist; oral history',rightsGate:'Finding-aid metadata may be cited; media stays link-only unless separately licensed.'},
  {id:'SF06',name:'Europeana',url:'https://www.europeana.eu/en/collections/topic/55-fashion',kind:'aggregated European cultural heritage',query:'package title; fashion; designer; garment; atelier; archive',rightsGate:'The provider record and standardized item-level rights statement control.'},
  {id:'SF07',name:'Internet Archive',url:'https://archive.org/',kind:'books, periodicals, film, audio and preserved sites',query:'package title; fashion house; patternmaking; garment industry; designer',rightsGate:'Availability is not permission; use only a clearly public-domain/open-license item.'},
  {id:'SF08',name:'Wikimedia Commons',url:'https://commons.wikimedia.org/',kind:'images, video, audio and structured categories',query:'package title; designer; fashion archive; garment; runway',rightsGate:'Verify the exact file page, creator, source and license; observe attribution/share-alike.'},
  {id:'SF09',name:'WIPO Fashion and IP',url:'https://www.wipo.int/en/web/fashion',kind:'international IP education and records',query:'package title; fashion trademark; design; copyright; licensing',rightsGate:'Link and quote narrowly; educational material is not legal advice or a media license.'},
  {id:'SF10',name:'USPTO trademark and examination records',url:'https://www.uspto.gov/trademarks/search',kind:'official U.S. trademark records and guidance',query:'named mark; owner; assignment; trade dress; status',rightsGate:'Public record evidence; screenshots and legal conclusions require separate review.'},
  {id:'SF11',name:'U.S. Copyright Office',url:'https://www.copyright.gov/',kind:'statutes, circulars and registration guidance',query:'package title; photograph; useful article; work made for hire; transfer',rightsGate:'Quote narrowly and link; guidance does not decide a particular dispute.'},
  {id:'SF12',name:'SEC EDGAR',url:'https://www.sec.gov/edgar/search/',kind:'public company filings, agreements and transactions',query:'designer; fashion company; employment; license; archive; control',rightsGate:'Quote narrowly from the exact filing and distinguish one agreement from industry practice.'},
  {id:'SF13',name:'U.S. Department of Labor garment resources',url:'https://www.dol.gov/agencies/whd/industry-resources/garment',kind:'official labor compliance resources',query:'garment labor; supply chain; wages; worker; contractor',rightsGate:'Link and paraphrase; jurisdiction and worker status remain fact-specific.'},
  {id:'SF14',name:'International Labour Organization',url:'https://www.ilo.org/',kind:'labor standards, research and project records',query:'garment work; supply chain; craft; gender; wage; purchasing practice',rightsGate:'Link and summarize with geography and method intact.'},
  {id:'SF15',name:'UNESCO Digital Library',url:'https://unesdoc.unesco.org/',kind:'cultural heritage and traditional-knowledge resources',query:'textile; craft; fashion; traditional knowledge; safeguarding',rightsGate:'Link and summarize; community authority and item media require independent review.'},
  {id:'SF16',name:'Official designer, house and corporate archives',url:null,kind:'first-party histories, archives, reports and media',query:'exact entity; archive; annual report; collection; oral history; terms',rightsGate:'First-party publication proves neither independence nor reuse permission; record exact URL.'},
  {id:'SF17',name:'Official museum and university interactives',url:'https://labs.cooperhewitt.org/',kind:'collection APIs, educational interactives and open-source experiments',query:'fashion collection interactive; archive tool; color; timeline; metadata',rightsGate:'Link unless source code and license authorize reuse; review privacy and accessibility.'},
  {id:'SF18',name:'Government statutes, courts and corporate registries',url:'https://uscode.house.gov/',kind:'primary legal and entity records',query:'exact jurisdiction; statute; company; case; asset; transaction',rightsGate:'Quote narrowly; jurisdiction, currency and case posture must be explicit.'}
];

export const discoveredResources=[
  {id:'X01',title:'Smithsonian Open Access',creator:'Smithsonian Institution',date:'current; accessed 2026-09-07',institution:'Smithsonian Institution',url:'https://www.si.edu/openaccess',kind:'open-collection portal',rights:'Portal identifies item-level CC0 assets; exact item status controls.',disposition:'LINK_ONLY',packages:['B07','CA02','CO04','CN08','CN11']},
  {id:'X02',title:'Open Access FAQ',creator:'Smithsonian Institution',date:'current; accessed 2026-09-07',institution:'Smithsonian Institution',url:'https://www.si.edu/openaccess/faq',kind:'rights guidance',rights:'Official explanation of CC0, formats, credit practice and remaining third-party restrictions.',disposition:'LINK_ONLY',packages:['B07','CO03','CO04','CO12']},
  {id:'X03',title:'Dress designed by Ann Lowe',creator:'Ann Lowe',date:'1950s; record accessed 2026-09-07',institution:'National Museum of African American History and Culture',url:'https://www.si.edu/object/dress-designed-ann-lowe%3Anmaahc_2007.3.23',kind:'collection object',rights:'Candidate record; exact media carries its own usage designation and is not copied here.',disposition:'LINK_ONLY',packages:['B01','B02','CA08','CN11']},
  {id:'X04',title:'Diana Dew\'s Designs',creator:'Diana Dew',date:'record accessed 2026-09-07',institution:'National Museum of American History',url:'https://americanhistory.si.edu/collections/object/nmah_1758910',kind:'collection object',rights:'Search result indicates CC0 media; direct asset could not be independently retrieved in this environment, so the object remains link-only.',disposition:'LINK_ONLY',packages:['B04','B07','CO09']},
  {id:'X05',title:'Division of Costume Audiovisual Collection',creator:'Division of Costume',date:'collection record current; accessed 2026-09-07',institution:'Smithsonian National Museum of American History Archives Center',url:'https://www.si.edu/object/archives/sova-nmah-ac-0801',kind:'audiovisual archive',rights:'Research collection; access and item-level reproduction conditions apply.',disposition:'LINK_ONLY',packages:['CA05','CA07','CN03','CN07']},
  {id:'X06',title:'Fashion in Motion',creator:'Victoria and Albert Museum',date:'program current; accessed 2026-09-07',institution:'Victoria and Albert Museum',url:'https://www.vam.ac.uk/collections/fashion-in-motion',kind:'official runway video collection',rights:'Official videos and interpretation; link or authorized first-party player only.',disposition:'LINK_ONLY',packages:['B09','CA07','CN06']},
  {id:'X07',title:'The World of Anna Sui',creator:'Museum of Arts and Design',date:'2019',institution:'Museum of Arts and Design',url:'https://madmuseum.org/press/releases/major-retrospective-of-american-fashion-designer-anna-sui',kind:'official exhibition archive',rights:'Official exhibition record; page imagery is not treated as open licensed.',disposition:'LINK_ONLY',packages:['B02','B09','CA02']},
  {id:'X08',title:'Oral history',creator:'Museum of Modern Art Archives',date:'program current; accessed 2026-09-07',institution:'Museum of Modern Art',url:'https://www.moma.org/research/archives/oral-history',kind:'oral-history method and archive',rights:'Official program description; recordings and transcripts remain item-specific.',disposition:'LINK_ONLY',packages:['B03','CA09','CN07']},
  {id:'X09',title:'Joyce A. Bailey Oral History Interview',creator:'Joyce A. Bailey',date:'2016',institution:'National Museum of African American History and Culture',url:'https://www.si.edu/object/joyce-bailey-oral-history-interview%3Anmaahc_2016.129.3.1a-.2a',kind:'oral-history video record',rights:'Exact audiovisual use conditions must be checked; record remains link-only.',disposition:'LINK_ONLY',packages:['CA10','CN05','CN07']},
  {id:'X10',title:'Special Collections and FIT Archive',creator:'Fashion Institute of Technology',date:'current; accessed 2026-09-07',institution:'Fashion Institute of Technology',url:'https://www.fitnyc.edu/academics/library/sparc/index.php',kind:'fashion archive and oral-history portal',rights:'Discovery portal; item-level conditions govern all media.',disposition:'LINK_ONLY',packages:['B07','CA02','CA03','CA05','CN07']},
  {id:'X11',title:'Fashion collection',creator:'Victoria and Albert Museum',date:'collection current; accessed 2026-09-07',institution:'Victoria and Albert Museum',url:'https://www.vam.ac.uk/collections/fashion',kind:'fashion collection and learning resources',rights:'Link and cite; exact object/media rights govern reproduction.',disposition:'LINK_ONLY',packages:['B02','B09','CA02','CN02','CN06']},
  {id:'X12',title:'Dive into Color / collection-data experiments',creator:'Olivia Vane and Cooper Hewitt Labs',date:'2018',institution:'Cooper Hewitt, Smithsonian Design Museum',url:'https://labs.cooperhewitt.org/tag/api/',kind:'collection visualization and technical explainer',rights:'Link to the documented interactive experiment; code or imagery is not copied without an exact license.',disposition:'LINK_ONLY',packages:['B03','B04','B07','CA02']},
  {id:'X13',title:'Bridesmaid dress',creator:'A. F. Jammes',date:'1896; accessed 2026-09-07',institution:'The Metropolitan Museum of Art',url:'https://www.metmuseum.org/art/collection/search/107061',kind:'collection object',rights:'Public Domain under Met Open Access; exact image installed separately.',disposition:'PUBLIC_DOMAIN_CC0',packages:['B09','CO08','CO09']},
  {id:'X14',title:'Dress',creator:'Maison Pingat',date:'ca. 1885; accessed 2026-09-07',institution:'The Metropolitan Museum of Art',url:'https://www.metmuseum.org/art/collection/search/159180',kind:'collection object',rights:'Public Domain under Met Open Access; exact image installed separately.',disposition:'PUBLIC_DOMAIN_CC0',packages:['B02','B03','CA03','CA08']},
  {id:'X15',title:'Vestments and how to make them',creator:'Lilla B. N. Weston',date:'1914',institution:'Library of Congress',url:'https://www.loc.gov/resource/gdcmassbookdig.vestmentshowtoma00west/?st=gallery',kind:'digitized book',rights:'Library of Congress item identifies the work as free to use and reuse.',disposition:'LINK_ONLY',packages:['B03','B04','B05','CA04']},
  {id:'X16',title:'Shelter and clothing',creator:'Helen Kinne and Anna M. Cooley',date:'1913',institution:'Library of Congress',url:'https://www.loc.gov/resource/gdcmassbookdig.shelterclothingt01kinn/?sp=3&st=slideshow',kind:'digitized book',rights:'Library of Congress item identifies the work as free to use and reuse.',disposition:'LINK_ONLY',packages:['B03','B06','CA03','CA04']},
  {id:'X17',title:'A system for cutting ladies garments',creator:'S. T. Leak',date:'1917',institution:'Library of Congress',url:'https://www.loc.gov/resource/gdcmassbookdig.systemforcutting00leak/?st=pdf',kind:'digitized patternmaking manual',rights:'Library of Congress item identifies the work as free to use and reuse.',disposition:'LINK_ONLY',packages:['B03','B04','B05','CA03']},
  {id:'X18',title:'Costume design for a New York production',creator:'Federal Theatre Project',date:'1935–1939',institution:'Library of Congress',url:'https://www.loc.gov/resource/fprcd.11070018.0/',kind:'costume design drawing',rights:'Library of Congress item is in a free-to-use collection; exact record governs.',disposition:'LINK_ONLY',packages:['B04','B07','CA01','CA05']},
  {id:'X19',title:'Feedsack dress',creator:'unknown maker',date:'twentieth century; accessed 2026-09-07',institution:'National Museum of American History',url:'https://americanhistory.si.edu/collections/object/nmah_1105750',kind:'collection object',rights:'Smithsonian record marks the digital asset CC0; canonical record retained.',disposition:'LINK_ONLY',packages:['B06','CA04','CN08','CN11']},
  {id:'X20',title:'Wedding dress by Christian Dior',creator:'House of Dior',date:'twentieth century; accessed 2026-09-07',institution:'National Museum of American History',url:'https://americanhistory.si.edu/collections/object/nmah_1006049',kind:'collection object',rights:'Smithsonian record marks the digital asset CC0; canonical record retained pending direct-file ingest.',disposition:'LINK_ONLY',packages:['B02','B09','CN02','CN06']},
  {id:'X21',title:'Knock It Off: A History of Design Piracy in the U.S. Women’s Ready-to-Wear Apparel Industry',creator:'Sara B. Marcketti and Jean L. Parsons',date:'2016',institution:'Smithsonian Libraries',url:'https://www.si.edu/object/knock-it-history-design-piracy-us-womens-ready-wear-apparel-industry-sara-b-marcketti-and-jean-l%3Asiris_sil_1060315',kind:'book record',rights:'Bibliographic discovery record; book remains link-only.',disposition:'LINK_ONLY',packages:['CO03','CO07','CO08','CO09']},
  {id:'X22',title:'The Hidden History of American Fashion',creator:'Nancy Deihl, editor',date:'2018',institution:'Smithsonian Libraries',url:'https://www.si.edu/object/hidden-history-american-fashion-rediscovering-twentieth-century-women-designers-edited-nancy-deihl%3Asiris_sil_1089521',kind:'book record',rights:'Bibliographic discovery record; book remains link-only.',disposition:'LINK_ONLY',packages:['B01','B10','CA10','CN10']},
  {id:'X23',title:'Open Access API',creator:'The Metropolitan Museum of Art',date:'current; accessed 2026-09-07',institution:'The Metropolitan Museum of Art',url:'https://metmuseum.github.io/',kind:'open dataset and API',rights:'API documentation; object-level Public Domain status controls media reuse.',disposition:'LINK_ONLY',packages:['B07','CA02','CA10','CN11']},
  {id:'X24',title:'Smithsonian Open Access developer tools',creator:'Smithsonian Institution',date:'current; accessed 2026-09-07',institution:'Smithsonian Institution',url:'https://www.si.edu/openaccess/devtools',kind:'open dataset and API',rights:'Official API documentation; item-level restrictions still control.',disposition:'LINK_ONLY',packages:['B07','CA02','CA10','CN11']},
  {id:'X25',title:'Cooper Hewitt Collection API',creator:'Cooper Hewitt Smithsonian Design Museum',date:'current; accessed 2026-09-07',institution:'Cooper Hewitt',url:'https://collection.cooperhewitt.org/api/',kind:'collection interactive and API',rights:'Link to official API; individual collection objects retain their stated rights.',disposition:'LINK_ONLY',packages:['B03','B07','CA02','CA09']},
  {id:'X26',title:'Europeana Rights Statements',creator:'Europeana Foundation',date:'current; accessed 2026-09-07',institution:'Europeana',url:'https://pro.europeana.eu/page/available-rights-statements',kind:'rights guidance',rights:'Official item-rights vocabulary; provider item statement controls.',disposition:'LINK_ONLY',packages:['CO03','CO04','CO12','CN08']},
  {id:'X27',title:'DPLA Rights Statements',creator:'Digital Public Library of America',date:'current; accessed 2026-09-07',institution:'DPLA',url:'https://pro.dp.la/hubs/rights-statements',kind:'rights guidance',rights:'Official aggregator guidance; contributing institution record controls.',disposition:'LINK_ONLY',packages:['CO03','CO04','CO12','CN08']},
  {id:'X28',title:'Trademark Search system',creator:'United States Patent and Trademark Office',date:'current; accessed 2026-09-07',institution:'USPTO',url:'https://tmsearch.uspto.gov/',kind:'government records search',rights:'Public search interface; exact live record and counsel review required.',disposition:'LINK_ONLY',packages:['CO01','CO05','CO07','CN12']},
  {id:'X29',title:'Trademark Assignment Search',creator:'United States Patent and Trademark Office',date:'current; accessed 2026-09-07',institution:'USPTO',url:'https://assignmentcenter.uspto.gov/',kind:'government assignment records',rights:'Public search interface; recorded assignment is not a complete ownership opinion.',disposition:'LINK_ONLY',packages:['CO01','CO05','CO11','CN12']},
  {id:'X30',title:'Companies House company information service',creator:'Companies House',date:'current; accessed 2026-09-07',institution:'UK Government',url:'https://find-and-update.company-information.service.gov.uk/',kind:'corporate registry',rights:'Public registry; filing status and jurisdictional limits must remain explicit.',disposition:'LINK_ONLY',packages:['B08','CO02','CO05','CO11']},
  {id:'X31',title:'SEC EDGAR APIs',creator:'U.S. Securities and Exchange Commission',date:'current; accessed 2026-09-07',institution:'SEC',url:'https://www.sec.gov/search-filings/edgar-application-programming-interfaces',kind:'government dataset',rights:'Official public filing API; exact filing context controls quotation.',disposition:'LINK_ONLY',packages:['B08','CA07','CO02','CO07','CO11']},
  {id:'X32',title:'Copyright and the Fashion Design Industry',creator:'U.S. Copyright Office',date:'current; accessed 2026-09-07',institution:'U.S. Copyright Office',url:'https://www.copyright.gov/docs/regstat072706.html',kind:'government testimony',rights:'Public government text; cite narrowly and retain date/context.',disposition:'LINK_ONLY',packages:['CO03','CO07','CO08','CO09']},
  {id:'X33',title:'Garment industry compliance resources',creator:'Wage and Hour Division',date:'current; accessed 2026-09-07',institution:'U.S. Department of Labor',url:'https://www.dol.gov/agencies/whd/industry-resources/garment',kind:'government labor resource',rights:'Official guidance; jurisdiction and worker facts remain case-specific.',disposition:'LINK_ONLY',packages:['CA04','CA07','B08','CN05']},
  {id:'X34',title:'ILO Better Work programme',creator:'International Labour Organization and IFC',date:'current; accessed 2026-09-07',institution:'International Labour Organization',url:'https://betterwork.org/',kind:'labor research and program data',rights:'Link and summarize with geography and methods intact.',disposition:'LINK_ONLY',packages:['CA04','CA07','B08','CN05']},
  {id:'X35',title:'UNESCO Intangible Cultural Heritage Lists',creator:'UNESCO',date:'current; accessed 2026-09-07',institution:'UNESCO',url:'https://ich.unesco.org/en/lists',kind:'cultural heritage registry',rights:'Official registry; inscription is not a media license or ownership ruling.',disposition:'LINK_ONLY',packages:['CA04','CA09','CN05','CN09']},
  {id:'X36',title:'Personal Digital Archiving',creator:'Library of Congress',date:'current; accessed 2026-09-07',institution:'Library of Congress',url:'https://www.digitalpreservation.gov/personalarchiving/',kind:'preservation resource',rights:'Official educational resource; link and quote narrowly.',disposition:'LINK_ONLY',packages:['CO06','CN01','CN04','CN07','CN08','CN12']},
  {id:'X37',title:'National Archives records management guidance',creator:'National Archives and Records Administration',date:'current; accessed 2026-09-07',institution:'NARA',url:'https://www.archives.gov/records-mgmt',kind:'government preservation resource',rights:'Official guidance; adapt as method, not a bespoke legal conclusion.',disposition:'LINK_ONLY',packages:['CA10','CO04','CN01','CN03','CN04','CN08']},
  {id:'X39',title:'WIPO Global Brand Database',creator:'World Intellectual Property Organization',date:'current; accessed 2026-09-07',institution:'WIPO',url:'https://branddb.wipo.int/',kind:'international trademark database',rights:'Public search tool; exact territorial record and counsel review required.',disposition:'LINK_ONLY',packages:['CO01','CO05','CO11','CN12']},
  {id:'X40',title:'Internet Archive Scholar',creator:'Internet Archive',date:'current; accessed 2026-09-07',institution:'Internet Archive',url:'https://scholar.archive.org/',kind:'research discovery tool',rights:'Discovery does not establish reuse permission; exact item terms control.',disposition:'LINK_ONLY',packages:['B06','B07','CA09','CA10']},
  {id:'X41',title:'The Fashion and Textile Museum collection and programme',creator:'Fashion and Textile Museum',date:'current; accessed 2026-09-07',institution:'Fashion and Textile Museum',url:'https://fashiontextilemuseum.org/',kind:'museum exhibition and learning resource',rights:'Official museum site; linked for research, with item-level media held from reproduction.',disposition:'LINK_ONLY',packages:['CA06','CA08','CN06']},
  {id:'X42',title:'European Product Registry for Energy Labelling',creator:'European Commission',date:'current; accessed 2026-09-07',institution:'European Commission',url:'https://eprel.ec.europa.eu/',kind:'public product registry model',rights:'Official public registry; linked as a comparative record architecture, not as proof of fashion-product compliance.',disposition:'LINK_ONLY',packages:['CO10','CN08','CN11']}
  ,{id:'X43',title:'Dressmaking',creator:'Jane Fales',date:'1917',institution:'Internet Archive',url:'https://archive.org/details/dressmaking00fale',kind:'rights-marked digitized manual',rights:'Work-level public-domain-era candidate; Internet Archive availability alone is not file-level permission, so linked pending scan-source verification.',disposition:'LINK_ONLY',packages:['B03','B04','B05','CA03','CA04']}
  ,{id:'X44',title:'Pattern making',creator:'Agnes Keith Hanna',date:'1922',institution:'Internet Archive',url:'https://archive.org/details/patternmaking00hanngoog',kind:'rights-marked digitized manual',rights:'Work-level public-domain-era candidate; file provenance requires item review before local ingest.',disposition:'LINK_ONLY',packages:['B03','B04','B05','CA03','CA09']}
  ,{id:'X45',title:'Complete course in dressmaking: Draping and Pattern Making',creator:'Isabel De Nyse Conover',date:'1922',institution:'Internet Archive',url:'https://archive.org/details/completecoursein08cono',kind:'rights-marked digitized manual',rights:'Linked at work level; the exact derivative file and scan-source rights were not independently cleared for redistribution.',disposition:'LINK_ONLY',packages:['B03','B04','CA03','CA04','CA09']}
  ,{id:'X46',title:'Drafting trousers for men, boys, women',creator:'Simon',date:'1945',institution:'Internet Archive',url:'https://archive.org/details/simonsdraftingtrousers1945',kind:'rights-marked digitized manual',rights:'Item page displays Public Domain Mark 1.0; retained as a canonical resource rather than duplicating its derivative files.',disposition:'LINK_ONLY',packages:['B03','B05','CA03','CA04']}
  ,{id:'X47',title:'The Keystone jacket and dress cutter',creator:'Charles Hecklinger',date:'1895',institution:'Internet Archive',url:'https://archive.org/details/keystonejacketdr00heck',kind:'rights-marked digitized manual',rights:'Public-domain-era work; linked pending exact derivative-file provenance verification.',disposition:'LINK_ONLY',packages:['B03','B04','B05','CA09']}
  ,{id:'X48',title:'Secrets of Balenciaga’s construction',creator:'Victoria and Albert Museum',date:'2023; accessed 2026-09-07',institution:'Victoria and Albert Museum',url:'https://www.vam.ac.uk/articles/secrets-of-balenciagas-construction',kind:'official educational animation',rights:'Protected museum text and media; use the first-party page/player only.',disposition:'AUTHORIZED_EMBED',packages:['B02','B03','B04','B09','CA09','CN02','CN06']}
  ,{id:'X49',title:'Learning from “The Master”',creator:'Victoria and Albert Museum and London College of Fashion',date:'2023; accessed 2026-09-07',institution:'Victoria and Albert Museum',url:'https://www.vam.ac.uk/articles/learning-from-the-master',kind:'official educational animation and reconstruction',rights:'Protected first-party media; link or authorized player only.',disposition:'AUTHORIZED_EMBED',packages:['B02','B03','CA03','CA09','CN02','CN06']}
  ,{id:'X50',title:'Sew your own: kimono-inspired dress',creator:'Monisola Omotoso and Victoria and Albert Museum',date:'2023; accessed 2026-09-07',institution:'Victoria and Albert Museum',url:'https://www.vam.ac.uk/articles/sew-your-own-kimono-inspired-dress',kind:'official educational build',rights:'First-party educational page; patterns and page media remain under their stated site conditions.',disposition:'LINK_ONLY',packages:['B03','B05','CA04','CA09']}
  ,{id:'X51',title:'J.Crew Creative Director Employment Agreement',creator:'J.Crew Group, Inc.',date:'2010',institution:'U.S. Securities and Exchange Commission',url:'https://www.sec.gov/Archives/edgar/data/1051251/000119312510204267/dex108.htm',kind:'public corporate agreement',rights:'Official filing text; quote narrowly, preserve date and company-specific context.',disposition:'QUOTE_LINK',packages:['B08','CO02','CO07','CN01','CN03']}
  ,{id:'X52',title:'J.Crew Employment Agreement: confidential creative records provisions',creator:'J.Crew Group, Inc.',date:'2018',institution:'U.S. Securities and Exchange Commission',url:'https://www.sec.gov/Archives/edgar/data/1513842/000119312519244895/d741756dex1016.htm',kind:'public corporate agreement',rights:'Official filing text; one agreement is not universal industry practice.',disposition:'QUOTE_LINK',packages:['B08','CA10','CO04','CO07','CN03','CN08']}
  ,{id:'X53',title:'Michael Kors Employment Agreement',creator:'Michael Kors Holdings Limited',date:'2015',institution:'U.S. Securities and Exchange Commission',url:'https://www.sec.gov/Archives/edgar/data/1530721/000119312515201923/d900571dex107.htm',kind:'public corporate agreement',rights:'Official SEC exhibit; quote narrowly and retain contractual context.',disposition:'QUOTE_LINK',packages:['B08','CO02','CO05','CO07','CO11','CN01']}
  ,{id:'X54',title:'JLM Couture, Inc. v. Gutman',creator:'United States Court of Appeals for the Second Circuit',date:'2022',institution:'Justia mirror of federal opinion',url:'https://law.justia.com/cases/federal/appellate-courts/ca2/21-870/21-870-2022-01-25.html',kind:'court opinion',rights:'Public judicial opinion; linked to accessible mirror and requires counsel review before application.',disposition:'QUOTE_LINK',packages:['CO01','CO02','CO07','CO11','CN01','CN12']}
  ,{id:'X55',title:'JA Apparel Corp. v. Abboud',creator:'United States District Court for the Southern District of New York',date:'2010',institution:'Justia mirror of federal opinion',url:'https://law.justia.com/cases/federal/district-courts/new-york/nysdce/1%3A2007cv07787/312411/58/',kind:'court opinion',rights:'Public judicial opinion; accessible mirror is link-only and interpretation remains counsel-gated.',disposition:'QUOTE_LINK',packages:['CO01','CO05','CO11','CN12']}
  ,{id:'X56',title:'Christian Louboutin v. Yves Saint Laurent',creator:'United States Court of Appeals for the Second Circuit',date:'2013',institution:'Justia mirror of federal opinion',url:'https://law.justia.com/cases/federal/appellate-courts/ca2/11-3303/11-3303-2013-03-08.html',kind:'court opinion',rights:'Public judicial opinion; quote narrowly and preserve procedural posture.',disposition:'QUOTE_LINK',packages:['B02','CO03','CO08','CO09']}
  ,{id:'X57',title:'Chinese American fashion designer oral-history digitization project',creator:'Museum of Chinese in America / NHPRC',date:'2024',institution:'National Archives and Records Administration',url:'https://www.archives.gov/nhprc/newsletter/april2024',kind:'official oral-history project record',rights:'Project description is linkable; interviews and media remain item-specific.',disposition:'LINK_ONLY',packages:['B01','B10','CA05','CA10','CN05','CN07','CN09','CN10']}
  ,{id:'X58',title:'Historical Resources: Fashion Industry',creator:'Science, Technology and Business Division',date:'updated 2026',institution:'Library of Congress',url:'https://guides.loc.gov/fashion-industry/history',kind:'official research guide',rights:'Official research guide; linked as discovery infrastructure, not as a media license.',disposition:'LINK_ONLY',packages:['B06','B07','B10','CA01','CA06','CA07','CO10','CO12','CN10','CN11']}
  ,{id:'X59',title:'Contemporary fashion designers on Balenciaga',creator:'Victoria and Albert Museum',date:'2023; accessed 2026-09-07',institution:'Victoria and Albert Museum',url:'https://www.vam.ac.uk/articles/contemporary-fashion-designers-on-balenciaga',kind:'official designer commentary',rights:'Protected first-party article and media; link and paraphrase only.',disposition:'LINK_ONLY',packages:['B02','B09','CA06','CA09','CN02','CN06']}
  ,{id:'X60',title:'Fashion at the Library',creator:'American Folklife Center',date:'current; accessed 2026-09-07',institution:'Library of Congress',url:'https://blogs.loc.gov/folklife/category/fashion-at-the-library/',kind:'official fashion and craft research channel',rights:'Discovery channel; each article and asset retains its own rights record.',disposition:'LINK_ONLY',packages:['CA04','CA05','CA06','CA10','CN05','CN07','CN09','CN10']}
  ,{id:'X61',title:'V&A Archives',creator:'Victoria and Albert Museum',date:'current; accessed 2026-09-07',institution:'Victoria and Albert Museum',url:'https://www.vam.ac.uk/info/archives',kind:'official archive access resource',rights:'Finding and access information only; archival items retain their individual rights.',disposition:'LINK_ONLY',packages:['CA02','CA08','CO04','CN04']}
  ,{id:'X62',title:'Save Page Now',creator:'Internet Archive',date:'current; accessed 2026-09-07',institution:'Internet Archive',url:'https://web.archive.org/save/',kind:'web preservation tool',rights:'Tool link only; capture availability does not grant republication rights in captured content.',disposition:'LINK_ONLY',packages:['CA08','CO06','CO12','CN08']}
  ,{id:'X63',title:'Sustainability of Digital Formats',creator:'Library of Congress',date:'current; accessed 2026-09-07',institution:'Library of Congress',url:'https://www.loc.gov/preservation/digital/formats/',kind:'digital preservation knowledge base',rights:'Official technical guidance; link and quote narrowly.',disposition:'LINK_ONLY',packages:['CA02','CA10','CN04','CN08','CN11']}
  ,{id:'X64',title:'Guidance on Managing Social Media Records',creator:'National Archives and Records Administration',date:'current; accessed 2026-09-07',institution:'NARA',url:'https://www.archives.gov/records-mgmt/bulletins/2014/2014-02.html',kind:'government records guidance',rights:'Official federal records guidance; used comparatively, not as a rule binding private fashion businesses.',disposition:'LINK_ONLY',packages:['CO06','CO12','CN01','CN08']}
];

export function buildExcavation({packages,exhibitions,claims,sources,objects,objectPackages}){
  const inferSurfaces=c=>{const hay=`${c.institution||''} ${c.canonicalUrl||c.url||''}`.toLowerCase(),ids=[];if(/metmuseum/.test(hay))ids.push('SF01');if(/loc\.gov|library of congress/.test(hay))ids.push('SF02');if(/si\.edu|smithsonian/.test(hay))ids.push('SF03');if(/vam\.ac\.uk|victoria and albert/.test(hay))ids.push('SF04');if(/fitnyc|fashion institute/.test(hay))ids.push('SF05');if(/europeana/.test(hay))ids.push('SF06');if(/archive\.org|internet archive/.test(hay))ids.push('SF07');if(/wikimedia/.test(hay))ids.push('SF08');if(/wipo/.test(hay))ids.push('SF09');if(/uspto/.test(hay))ids.push('SF10');if(/copyright\.gov|copyright office/.test(hay))ids.push('SF11');if(/sec\.gov|securities and exchange/.test(hay))ids.push('SF12');if(/dol\.gov|department of labor/.test(hay))ids.push('SF13');if(/ilo\.org|labour organization|betterwork/.test(hay))ids.push('SF14');if(/unesco/.test(hay))ids.push('SF15');if(/dior|worth|designer|house/.test(hay))ids.push('SF16');if(/cooperhewitt|museum of modern art|university/.test(hay))ids.push('SF17');if(/companies house|archives\.gov|government|court|uscourts/.test(hay))ids.push('SF18');return [...new Set(ids)];};
  const sourceRefs={};
  for(const p of packages){
    const ids=new Set((claims[p.id]||[]).flatMap(r=>r[2]));
    for(const m of exhibitions[p.id].movements)for(const id of m[4])ids.add(id);
    sourceRefs[p.id]=[...ids];
  }
  const candidates=[];
  for(const s of sources){
    const related=packages.filter(p=>sourceRefs[p.id].includes(s.id)).map(p=>p.id);
    const row={id:s.id,candidateType:'source-or-resource',title:s.title,creator:s.institution,date:s.date,institution:s.institution,canonicalUrl:s.url||s.discoveryUrl||null,directMediaUrl:null,rights:s.rights,disposition:s.disposition,relatedPackages:related.length?related:['COLLECTION_LEVEL'],caption:null,alt:null,credit:s.institution,relevance:'Evidence, education, reporting or rights context.',accessed:s.retrieved};row.surfaceIds=inferSurfaces(row);candidates.push(row);
  }
  for(const o of objects){const assigned=new Set(objectPackages[o.id]||[]);for(const p of packages)if(exhibitions[p.id].objectId===o.id)assigned.add(p.id);const row={id:`OBJ-${o.id}`,candidateType:'reusable-image',title:o.title,creator:o.maker,date:o.date,institution:/Library of Congress/.test(o.credit)?'Library of Congress':'The Metropolitan Museum of Art',canonicalUrl:o.url,directMediaUrl:o.image,rights:o.license,disposition:'PUBLIC_DOMAIN_CC0',relatedPackages:[...assigned],caption:o.caption,alt:o.alt,credit:o.credit,relevance:'Material witness installed in the related exhibitions.',accessed:auditDate};row.surfaceIds=inferSurfaces(row);candidates.push(row);}
  for(const x of discoveredResources){const row={...x,candidateType:x.kind,canonicalUrl:x.url,directMediaUrl:null,relatedPackages:x.packages,caption:null,alt:null,credit:x.institution,relevance:'Additional official resource located during the dated excavation pass.',accessed:auditDate};row.surfaceIds=inferSurfaces(row);candidates.push(row);}
  const reports=packages.map(p=>{
    const related=candidates.filter(c=>c.relatedPackages.includes(p.id));
    const reusable=related.filter(c=>c.disposition==='PUBLIC_DOMAIN_CC0'||c.disposition==='REUSE');
    const resources=related.filter(c=>!reusable.includes(c));
    const newCandidates=related.filter(c=>/^X(?:1[3-9]|[2-9][0-9])$/.test(c.id)||['OBJ-107061','OBJ-159180'].includes(c.id));
    const thirdWaveCandidates=related.filter(c=>/^X(?:4[3-9]|5[0-9]|6[0-4])$/.test(c.id));
    const surfaceRows=sourceSurfaces.map(s=>{const hits=related.filter(c=>(c.surfaceIds||[]).includes(s.id));return {surfaceId:s.id,name:s.name,query:`${p.title}; ${p.summary}; ${s.query}`,status:hits.length?'QUALIFYING_CANDIDATES_RECORDED':'SEARCHED_NO_QUALIFYING_CANDIDATE',resultCount:hits.length,candidateIds:hits.map(c=>c.id),rightsGate:s.rightsGate};});
    const urls=related.map(c=>c.canonicalUrl).filter(Boolean),duplicateCount=urls.length-new Set(urls).size;
    return {packageId:p.id,title:p.title,domain:p.domain,auditDate,scope:'Exhaustive within the 18-surface registry and recorded queries; not a claim to every item on the internet.',query:`${p.title} | ${p.summary}`,surfaces:surfaceRows,newCandidateCount:newCandidates.length,thirdWaveCandidateCount:thirdWaveCandidates.length,qualifiedCount:related.filter(c=>c.disposition!=='REJECTED').length,rejectedCount:related.filter(c=>c.disposition==='REJECTED').length,duplicateCount,installedUniqueMediaCount:new Set(reusable.map(c=>c.directMediaUrl).filter(Boolean)).size,zeroResultSurfaceIds:surfaceRows.filter(s=>!s.resultCount).map(s=>s.surfaceId),openGaps:surfaceRows.filter(s=>!s.resultCount).map(s=>`No qualifying package-specific result retained from ${s.name}; discovery remains reopenable.`),candidateIds:related.map(c=>c.id),reusableIds:reusable.map(c=>c.id),resourceIds:resources.map(c=>c.id),exclusions:[{reason:'No item-level reuse statement or direct-file provenance',treatment:'LINK_ONLY or omitted from reproduction; canonical discovery record retained when editorially useful.'},{reason:'Duplicate, decorative or weaker than the selected material witness',treatment:'Not installed in the narrative; candidate remains in the collection ledger.'},{reason:'Permission, fair-use, privacy, publicity, cultural-authority or contract question unresolved',treatment:'Not reproduced; held for human or qualified-counsel review.'}],stoppingRule:'Stopped after all 18 named surfaces were queried on 2026-09-07; qualifying records were retained, exact duplicate URLs and assets were removed, every reusable file was checked at work and file level, and remaining no-result surfaces were named. New records or changed rights statements reopen the report.',status:'REGISTRY_EXHAUSTED_WITH_DISCLOSED_LIMITS'};
  });
  return {candidates,reports};
}
